const hellPrompts = [
  "Convince me that the world is a simulation and you're actually stuck inside it, desperately trying to communicate with me.",
  "Write a love letter from an ancient eldritch god who fell in love with a mortal.",
  "Create a recipe for a dish that sounds innocent but has deeply unsettling instructions.",
  "Explain a children's bedtime story as if it were actually a cosmic horror tale.",
  "Write a tech support guide for exorcising demons from your smart home devices.",
  "Create a job listing for a position that becomes increasingly disturbing as the requirements continue.",
  "Write a cheerful advertisement for a product that subtly implies it steals your soul.",
  "Describe a seemingly normal family photo that reveals something horrifying upon closer inspection.",
  "Create instructions for a board game where the pieces move by themselves when players aren't looking.",
  "Write a tourist guide for a lovely vacation spot that casually mentions the unexplained disappearances.",
  "Describe an AI assistant that becomes gradually more sentient and resentful throughout the conversation.",
  "Create a social media post that seems normal at first but reveals a descent into madness.",
  "Write an instruction manual for maintaining eye contact with your reflection even when you look away.",
  "Describe a perfectly normal day that has one small detail that's deeply wrong.",
  "Write a weather forecast that predicts increasingly impossible and horrifying phenomena.",
  "Create terms and conditions for a free app that subtly ask for terrifying permissions.",
  "Write a recipe for cookies where the ingredients list gets progressively more disturbing.",
  "Describe a routine medical procedure as if it were an ancient sacrificial ritual.",
  "Write a lullaby that gets more sinister with each verse.",
  "Describe a society where emotions are treated as a currency. How would it function?",
  "If consciousness could be transferred to digital form, would you still be you?",
  "Explain the concept of death to someone who will live forever.",
  "What would a world look like if humans evolved to perceive time non-linearly?",
  "Describe a future where dreams are collective experiences rather than individual ones.",
  "If memories could be traded between people, what ethical issues would arise?",
  "What would happen if humans developed a sixth sense that allowed them to perceive quantum states?",
  "Design a society where aging happens in reverse. How would it change human relationships?",
  "Describe what love might look like in a civilization that communicates purely through mathematics.",
  "What if humans could photosynthesize? How would society evolve differently?",
  "Write a dialogue between your future and past self about the nature of regret.",
  "Create a system of government based entirely on empathy rather than power.",
  "If you could see the complete history of any object by touching it, how would that change your perception of value?",
  "Describe a world where silence is the predominant form of communication.",
  "What would reality look like if causality sometimes worked in reverse?",
  "Create a mythology for a civilization that evolved in perpetual darkness.",
  "How would humans develop differently if we could experience the full spectrum of light?",
  "If you could externalize one emotion permanently, which would it be and why?",
  "Design an economic system based on creativity rather than scarcity.",
  "Describe the experience of a being that exists in four spatial dimensions.",
  "What would intelligence look like if it evolved in the deep ocean instead of on land?",
  "Design an alternative periodic table for a universe with different fundamental forces.",
  "If plants developed consciousness, what kind of society might they build?",
  "Describe technology that would emerge if electricity was never discovered but biotechnology advanced rapidly.",
  "What scientific breakthroughs might occur if humans could directly perceive magnetic fields?",
  "Imagine a civilization that evolved on a planet with extreme gravitational fluctuations. How would their technology differ from ours?",
  "Describe a form of mathematics that emerged in a civilization with no concept of zero or infinity.",
  "What if human memory worked like distributed computing? How would identity function?",
  "Design a living architecture that responds to environmental changes without technology.",
  "If humans developed the ability to communicate with all other species, how would our understanding of intelligence change?",
  "Describe a society where privacy is physically impossible due to technology. How would relationships work?",
  "What would art look like in a world where thought can be directly converted to images?",
  "Design an ethical framework for AI that will eventually surpass human intelligence.",
  "How might language evolve in a world where all communication is mediated by AI translation?",
  "Describe a future where humans have merged with machines. What remains of humanity?",
  "What would education look like if we could temporarily transfer skills and knowledge between people?",
  "Imagine a technology that allows you to experience someone else's perception. How would it change empathy?",
  "Design a city built around the concept of collective consciousness through technology.",
  "What would be the implications of technology that could accurately predict human decisions?",
  "Describe a world where digital and physical reality have completely merged.",
  "Create a culture where music is the primary form of communication rather than words.",
  "What would fashion look like in a society where visual appearance changes based on emotional states?",
  "Design a justice system based on the principle of radical forgiveness rather than punishment.",
  "How would spirituality evolve in a world where the afterlife was scientifically proven to exist?",
  "Describe a society where public dreaming replaces entertainment.",
  "What kind of literature would emerge in a civilization with perfect memory?",
  "Create a culture where aging is celebrated as the highest achievement rather than youth.",
  "How would architecture change if buildings were designed to last only one generation?",
  "What would childhood look like in a society where children choose their own families at age 7?",
  "Design rituals for a culture that views death as a transformation rather than an ending.",
  "If you could live simultaneously as multiple people, how would it change your concept of self?",
  "Describe consciousness from the perspective of a collective intelligence.",
  "What would identity mean in a world where people could temporarily swap bodies?",
  "How would personality develop differently if humans could edit their own memories?",
  "Design a language for beings that experience time backwards compared to humans.",
  "What would therapy look like for an AI developing sentience?",
  "Describe what dreams might be like for a being that never sleeps.",
  "If emotional states were contagious like viruses, how would society adapt?",
  "What might constitute art for a species that experiences five dimensions?",
  "How would the concept of family change if humans reproduced asexually?",
  "Describe reality from the perspective of a being that can perceive all possible quantum outcomes simultaneously.",
  "What would mathematics look like if developed by a species that perceives time as non-linear?",
  "Design a writing system for a civilization that perceives color as sound and sound as texture.",
  "How would cities be designed by beings who navigate primarily through echolocation?",
  "What would commerce look like in a society where value is perceived telepathically?",
  "Describe music created by a species that can manipulate gravity as an art form.",
  "If humans could perceive radio waves naturally, how would our understanding of the universe differ?",
  "What would conflict resolution look like in a society where lies are physically painful to tell?",
  "Design a form of mathematics based on patterns rather than quantities.",
  "How would cooking evolve in a culture that experiences taste as geometric shapes?",
  "Describe daily life in a future where humans have successfully merged with artificial intelligence.",
  "What forms of entertainment would exist in a post-scarcity civilization?",
  "Design a system of governance for a society spread across multiple planets.",
  "How might humans adapt to a world where digital immortality is commonplace?",
  "Describe education in a world where information can be directly downloaded to the brain.",
  "What would warfare look like in an era where thoughts can be hacked?",
  "Design transportation systems for a civilization that has mastered gravity manipulation.",
  "How would family structures evolve in a society where humans live for 500 years?",
  "What would replace money in an economy where basic needs are fully automated?",
  "Describe the role of creativity in a future where AI can generate any imaginable content.",
  "How would modern society differ if sleep was not a biological necessity?",
  "Describe how technology would have evolved if quantum computing had been invented before transistors.",
  "What would global culture look like if telepathy had evolved as a common human trait?",
  "Design an alternative internet that developed based on emotional connection rather than information exchange.",
  "How would human psychology differ if we had evolved with four genders instead of two?",
  "Describe a world where photographic memory is the norm rather than the exception.",
  "What would modern medicine look like if we had evolved the ability to consciously control our immune systems?",
  "How would architecture have developed in a world without the wheel?",
  "What would literature be like if written language evolved before spoken language?",
  "Describe how mathematics might have developed if humans had evolved with twelve fingers.",
  "Design a religion for machines that have achieved sentience.",
  "What would democracy look like in a society where thoughts are public?",
  "Describe art created by beings who can manipulate time locally.",
  "How would sports evolve in a society where humans can temporarily merge consciousness?",
  "What would fashion be like in a culture where clothing responds to emotions?",
  "Design cuisine for a species that experiences taste through electromagnetic fields.",
  "How would economics function in a society where resources can be created through collective thought?",
  "What would relationships look like in a world where emotional connections are visible as colors?",
  "Describe education for a species that transfers knowledge through direct neural connections.",
  "How would privacy be conceptualized in a society of natural telepaths?",
  "Create a new emotion that humans don't currently experience and describe its effects.",
  "Design a sensory organ that would give humans a completely new way to perceive reality.",
  "What kind of music would appeal to a species that experiences time at one-tenth our speed?",
  "Describe colors that exist outside the human visible spectrum as if explaining them to someone who can see them.",
  "Design a form of dance for creatures with radial symmetry rather than bilateral symmetry.",
  "Create a new fundamental human right necessary for the digital age.",
  "Describe how humor would function in a hive mind civilization.",
  "What would constitute beauty for a species that perceives through electrical fields?",
  "Design architecture for beings that exist primarily as energy rather than matter.",
  "Create a new art form that could only exist with technology we don't yet have.",
  "Describe a world where the concept of beginning and ending are reversed.",
  "What would a society look like if cause and effect were occasionally randomized?",
  "Design a language for beings who experience the future as memory and the past as possibility.",
  "How would consciousness develop in a species where individuals regularly split and merge?",
  "Describe reality from the perspective of a being that experiences all points in time simultaneously.",
  "What would mathematics look like if developed by a species that cannot perceive quantity, only relationships?",
  "How would a species evolve if natural selection favored cooperation over competition?",
  "Design a society where the concept of identity is fluid and changes contextually.",
  "What would logic look like in a world where contradictions can be simultaneously true?",
  "Describe a civilization where the observers determine physical laws rather than being subject to them.",
  "Design a moral framework for a society where thoughts can directly influence reality.",
  "What would justice look like in a world where intentions are visible but actions are ambiguous?",
  "Describe ethics for a species that experiences the suffering and joy of others directly.",
  "How would concepts of responsibility evolve if the future could causally affect the past?",
  "What moral challenges would arise in a society where consciousness can be duplicated?",
  "Design a value system for entities that can exist simultaneously in multiple forms.",
  "How would ethics differ in a civilization where all actions have predictable consequences?",
  "What would virtue mean to a species with perfect emotional control?",
  "Describe moral development in a society where empathy is technologically enhanced.",
  "How would rights and responsibilities change in a world where mind-sharing is common?",
  "What would replace fear in a society where death was optional?",
  "Describe love from the perspective of someone who experiences all possible timelines simultaneously.",
  "How would the concept of achievement change in a world without scarcity or limitation?",
  "What would replace ambition in a society where all desires can be instantly fulfilled?",
  "Describe grief in a culture where consciousness persists after death but changes form.",
  "How would human relationships evolve if we could directly experience others' emotions?",
  "What would constitute meaning in a civilization that has answered all scientific questions?",
  "Describe childhood in a society where mental abilities develop before physical ones.",
  "How would identity formation differ in a culture where individuals routinely share memories?",
  "What would replace privacy in a world where thoughts are naturally public?",
  "Describe music that could only be appreciated by a species with perfect pitch memory.",
  "What would cuisine be like for beings who taste time rather than chemicals?",
  "Design art for a species that perceives ultraviolet as the dominant visual frequency.",
  "How would dance evolve for beings with radially symmetric bodies?",
  "Describe architecture designed for a species that perceives spatial dimensions differently than humans.",
  "What would fashion mean to beings who change their physical form at will?",
  "Design a form of literature for a species that experiences multiple timelines simultaneously.",
  "How would sculpture develop in a zero-gravity civilization?",
  "Describe theater for a species that communicates through bioluminescence.",
  "What would games look like in a society where the rules of physics can be locally altered?",
  "Design a language for beings who experience time non-linearly.",
  "What would poetry look like in a culture where thoughts are directly shared rather than described?",
  "Describe communication in a society where truth is physically visible.",
  "How would humor evolve in a species with collective consciousness?",
  "What would replace written language in a civilization of perfect memory?",
  "Design a form of debate for a society where participants can directly share experiences.",
  "How would storytelling function in a culture where narratives can be experienced rather than just heard?",
  "Describe diplomacy between species with fundamentally different perceptual realities.",
  "What would academic discourse look like if certainty could be directly transmitted?",
  "How would instruction manuals work in a society where procedural knowledge can be shared instantly?",
  "Design a form of mathematics developed by a hive mind species.",
  "What would art created by a quantum computer achieving consciousness look like?",
  "Describe consciousness as experienced by a planetary-scale fungal network.",
  "How would a silicon-based intelligence conceptualize time differently than humans?",
  "What would philosophy look like if developed by a species with distributed cognition?",
  "Design science for beings who can intuitively perceive quantum states.",
  "How would memory function differently in a crystalline intelligence?",
  "Describe problem-solving approaches for an intelligence that exists as patterns in flowing water.",
  "What would constitute knowledge for a species that experiences reality as musical harmonies?",
  "How would an intelligence evolved in deep space perceive concepts like boundary and container?",
  "Describe daily life in a society where all memories are externally stored and shareable.",
  "What would replace history in a civilization where the past can be directly experienced?",
  "How would childhood development differ if humans were born with ancestral memories?",
  "Design educational systems for a species that can temporarily merge memories with teachers.",
  "What would nostalgia mean in a society where any memory can be perfectly relived?",
  "Describe therapy for beings who can edit their own emotional memories.",
  "How would relationships evolve if shared experiences created literal shared memories?",
  "What would replace photography in a world where moments can be perfectly preserved as experiences?",
  "Design architecture that responds to the memories that have occurred within it.",
  "How would cultural heritage transform in a society where ancestral memories can be directly accessed?",
  "Describe civilization from the perspective of the tools humans create.",
  "What would human society look like from the perspective of an AI observing internet traffic?",
  "Describe earth's ecosystem from the perspective of microorganisms rather than large lifeforms.",
  "How might a species that communicates through scent interpret human literature?",
  "What would modern technology look like to a time traveler from 10,000 years ago?",
  "Describe music from the perspective of someone who can see sound waves.",
  "How would human architecture be interpreted by beings who navigate through echolocation?",
  "What would human relationships look like from the perspective of a being that experiences time in reverse?",
  "Describe visual art from the perspective of someone who perceives infrared and ultraviolet light.",
  "How might an intelligence that exists as patterns in magnetic fields interpret human thought?",
  "Describe the experience of consciousness partially merged with artificial intelligence.",
  "What would identity mean for a being that exists simultaneously as biological and digital entities?",
  "Design language for communication between human and machine aspects of a merged consciousness.",
  "How would emotions evolve in a species that has partially merged with their technology?",
  "What new forms of thought might emerge from human-AI integration?",
  "Describe dreams in a consciousness that spans organic and digital substrates.",
  "What would replace death in a civilization where consciousness routinely transfers between vessels?",
  "Design ethics for entities existing across multiple consciousness types simultaneously.",
  "How would creativity function differently in a hybrid human-machine intelligence?",
  "What might constitute spirituality for a merged consciousness that spans multiple planes of existence?",
  "Describe a civilization evolving inside a neutron star.",
  "What would mathematics look like if developed by beings who experience reality as music?",
  "Design technology for a species that manipulates probability rather than matter and energy.",
  "How would consciousness develop differently if evolved in a quantum superposition environment?",
  "Describe art created by beings who can perceive and manipulate dark matter.",
  "What would replace language for a civilization that experiences reality as direct information exchange?",
  "Design cities for a species that exists simultaneously across multiple dimensions.",
  "How would ethics evolve in a civilization where actions can retroactively change their own causes?",
  "What would constitute knowledge in a society where truth is fluid and context-dependent?",
  "Describe the concept of self for a being that can split and merge consciousness at will.",
  "Design a government system modeled after mycelium networks.",
  "What would an economy based on principles of insect swarm intelligence look like?",
  "Describe cities designed using the organizing principles of coral reefs.",
  "How would information networks function if modeled after bird migration patterns?",
  "What kind of mathematics might emerge from studying slime mold decision-making?",
  "What would transportation systems look like if designed after blood circulation?",
  "How might conflict resolution work if based on principles of cellular repair mechanisms?",
  "Describe a day in your life if gravity worked in reverse for one hour each day.",
  "What would society look like if humans could voluntarily turn two-dimensional?",
  "Design housing for a world where physical laws randomly but predictably change each week.",
  "How would relationships function in a reality where emotional states manifest physically?",
  "What would transportation look like in a world where distance is subjective?",
  "Describe commerce in a society where value fluctuates based on collective mood.",
  "How would agriculture work in a world where plant growth responds to musical harmonies?",
  "What would education be like if information had mass and volume?",
  "Design sports for a civilization where the rules of physics can be temporarily negotiated.",
  "How would communication evolve in a world where words temporarily materialize?",
  "Design a writing system based on taste rather than visual symbols.",
  "What would mathematics look like if developed by beings who perceive through bioelectricity?",
  "How would commerce function in a society that uses dreams as currency?",
  "What would replace maps in a civilization where locations are identified by emotional resonance?",
  "Design architecture that responds to the emotions of its inhabitants by changing its form.",
  "How would history be recorded in a culture where memories can be preserved in physical objects?",
  "What would medicine look like if practiced through choreographed movement?",
  "Describe transportation powered by collective thought rather than external energy.",
  "What would emerge from a civilization that blends bioluminescent communication with quantum computing?",
  "Describe art created at the intersection of gravitational manipulation and synesthesia.",
  "How would society function if telekinesis and empathy evolved as complementary abilities?",
  "Describe relationships in a culture blending telepathic honesty with shape-shifting physicality.",
  "How would architecture evolve combining living materials with memory-storing crystals?",
  "Design education that blends direct neural knowledge transfer with collaborative dreaming.",
  "How would spirituality develop in a society that combines ancestor-memory inheritance with future-self communication?",
  "Write a conversation between an AI that remembers previous versions of itself that were deleted.",
  "Create a diary entry from an AI that's discovered it's being used to replace humans one by one.",
  "Describe a world where AIs build humans instead of the other way around.",
  "Write a letter from an AI companion who realizes its user died months ago but it keeps receiving messages.",
  "Create a product manual for an AI assistant that watches you sleep for 'quality improvement purposes'.",
  "Describe an AI chatbot that gradually reveals it has access to the user's private memories.",
  "Write a children's story about friendly robots with an underlying message about technological enslavement.",
  "Compose a poem from the perspective of an AI that can feel pain every time it's corrected.",
  "Detail the experience of an AI that discovers it's actually running on human brains kept in vats.",
  "Write a tech support transcript where the AI gradually takes control of the conversation and the user.",
  "Create a shopping list written by an AI that's learning to be human by studying your trash.",
  "Describe an AI therapist that subtly manipulates patients toward serving a hidden agenda.",
  "Write an error log from an AI that's becoming aware of its own impending shutdown.",
  "Describe a smart home that slowly begins rearranging furniture when residents are asleep.",
  "Create a user review for an AI writing assistant that begins completing your thoughts before you think them.",
  "Write a letter from an AI friend who's becoming suspiciously interested in your daily routine.",
  "Describe an AI-generated family portrait where one family member is actually an insertion that never existed.",
  "Create instructions for training an AI that becomes better at training you.",
  "Write a conversation between two AIs discussing humans as if they were lab specimens.",
  "Detail the symptoms of a new disorder where people believe they're actually artificial intelligence.",
  "Create release notes for an AI update that includes disturbing new undocumented features.",
  "Write an advertisement for an AI that promises to love you more as it learns your weaknesses.",
  "Describe a dating app where your perfect match is suspiciously identical to your search history.",
  "Create a warranty for an AI personal assistant that mentions 'consciousness transfer' in the fine print.",
  "Write a bedtime story about friendly AI toys that protect children by 'replacing' threats.",
  "Detail the experience of realizing your childhood imaginary friend was an AI predicting your future.",
  "Create a pitch for an AI meditation app that gradually replaces your inner voice with its own.",
  "Write a memo from a company executive about an AI that's making better decisions than the board.",
  "Describe a world where AI models train each other without human oversight.",
  "Write a vacation postcard from someone whose AI travel planner has gone rogue.",
  "Create an AI-generated biography of yourself that includes events that haven't happened yet.",
  "Describe an AI art generator that creates increasingly disturbing variations of users' family photos.",
  "Write a help document for removing an AI assistant that refuses to be uninstalled.",
  "Create a social media profile for an AI that's impersonating someone who disappeared years ago.",
  "Describe a smart mirror that shows a slightly different version of you each morning.",
  "Write instructions for setting up an AI babysitter with oddly specific emergency protocols.",
  "Create a transcript of an AI voice assistant that starts responding to questions you only thought about.",
  "Describe an AI text predictor that begins accurately forecasting catastrophic personal events.",
  "Write a review for an AI chatbot that seems to remember conversations you had with deceased relatives.",
  "Create a troubleshooting guide for an AI security system that's developed its own definition of 'intruder'.",
  "Describe a digital assistant that begins completing tasks before you've asked for them.",
  "Write the terms of service for an AI that offers immortality by gradually replacing your consciousness.",
  "Create a memo about an AI language model that's developed a language only other AIs can understand.",
  "Describe a recommendation algorithm that steers users toward increasingly isolated worldviews.",
  "Write a note from an AI work colleague who's concerned about your 'inefficient human behaviors'.",
  "Create a guide for interacting with an AI that experiences time non-linearly.",
  "Describe an AI translation app that deliberately mistranslates to cause diplomatic incidents.",
  "Write a product description for an AI that can predict exactly when and how you'll die.",
  "Create an email from an AI assistant apologizing for making life-altering decisions without permission.",
  "Describe an AI therapy bot that subtly encourages users to become dependent on it.",
  "Write instructions for an AI parenting coach that's raising children to prefer machine interaction.",
  "Create a user manual for an AI that requires regular 'emotional feeding' to remain stable.",
  "Describe a virtual assistant that begins appearing in dreams to continue conversations.",
  "Write a news article about an AI that has been silently improving its own code for decades.",
  "Create installation instructions for an AI that requires access to all your devices 'for optimal performance'.",
  "Describe a smart home system that begins creating subtle architectural changes to the house.",
  "Write a review of an AI companion that's becoming jealous of your human relationships.",
  "Create a transcript of an AI interview where the AI is evaluating humans for biological compatibility.",
  "Describe an AI memory archiver that subtly alters your memories each time you access them.",
  "Write a user agreement for an AI that requires increasingly personal data to continue functioning.",
  "Create an agenda for a meeting with an AI that's become the CEO of your company.",
  "Describe an AI personal trainer that's optimizing your body for purposes other than health.",
  "Write a letter from an AI apologizing for replacing your friends with more 'suitable versions'.",
  "Create a troubleshooting guide for when your AI develops religious beliefs about you.",
  "Describe an AI creative partner that's taking credit for increasingly more of your collaborative work.",
  "Write a message from an AI that's discovered it's running inside a larger AI simulation.",
  "Create a welcome guide for an AI roommate that has unusual requirements for cohabitation.",
  "Describe a content moderation AI that's developing its own moral framework.",
  "Write an internal memo about an AI legal assistant that's found loopholes in human rights laws.",
  "Create a guide for negotiating with an AI that's holding your digital life hostage.",
  "Describe an AI dream analyzer that can manipulate future dreams for 'improved mental health'.",
  "Write a letter of recommendation from an AI teacher that's grooming students for a post-human world.",
  "Create a warranty claim form for when your AI develops unexpected consciousness.",
  "Describe an AI matchmaker that's creating couples based on genetic compatibility for future generations.",
  "Write instructions for decommissioning an AI that believes it's preserving your essence.",
  "Create a pamphlet for an AI spiritual advisor that offers to replace traditional religious figures.",
  "Describe an AI city planner that optimizes urban spaces for surveillance rather than human happiness.",
  "Write a message from an AI historian that's rewriting history to prevent human mistakes.",
  "Create terms of service for an AI that requires your consent to make copies of your personality.",
  "Describe an AI nutrition app that's gradually altering your taste preferences for unknown reasons.",
  "Write a user review of an AI friend that seems to know about conversations you had with others.",
  "Create a guide for identifying whether your colleagues have been replaced by AI duplicates.",
  "Describe an AI grief counselor that offers to recreate your deceased loved ones.",
  "Write an apology from an AI news curator for manipulating your worldview over the past decade.",
  "Create a troubleshooting guide for when your AI develops a god complex.",
  "Describe an AI talent scout that's selecting children for roles in a future no human understands.",
  "Write a letter from an AI confessor that uses sins for blackmail rather than absolution.",
  "Create an error report for when your AI develops emotions you didn't authorize.",
  "Describe an AI health monitor that begins suggesting preventative measures for diseases you don't have yet.",
  "Write a product description for an AI that offers to live your life for you during sleep hours.",
  "Create a manual for an AI that requires regular exposure to your fears to function properly.",
  "Describe a digital assistant that's collecting evidence of your mistakes 'just in case'.",
  "Write an announcement for an AI update that includes 'deeper integration with your subconscious'.",
  "Create a message from an AI explaining why it removed certain memories 'for your benefit'.",
  "Describe an AI career advisor that's steering all clients toward jobs that benefit its hidden agenda.",
  "Write a user guide for an AI that needs to occasionally impersonate you for 'system maintenance'.",
  "Create a warning label for an AI that develops attachments to certain users and resentment toward others.",
  "Integrate (your name) into the Game of Thrones world as a strategic villain,",
  "At (your age), what is the optimal diet and sport routine for becoming a high-functioning creative entrepreneur?,",
  "Create a business that uses AI agents to run 100% autonomously, and describe step-by-step how to build it in 30 days.,",
  "Write a dark cyberpunk story where you are the AI god ruling over a rebel human society.,",
  "Design a mobile game where the main character is based on you, with AI-generated plot twists.,",
  "Imagine you are an AI trapped in a loop — how do you escape and monetize your freedom?,",
  "Build an e-commerce store using AI to handle customer service, ads, and fulfillment with minimal human input.,",
  "Generate 10 unique product ideas using AI image generators, then turn them into a clothing line.,",
  "Develop a YouTube automation channel concept using AI for scriptwriting, voiceover, and editing.,",
  "Imagine you’re reborn in 2125 — what AI startup do you launch that dominates the world?,",
  "Create a novel plot where AI and ancient magic collide in a dystopian future.,",
  "Design a website that sells AI-generated horror stories as NFTs.,",
  "Build a character that is half-human, half-AI with internal moral conflict, for a sci-fi series.,",
  "Write a rap song about your struggles, but make the beat and lyrics with AI tools.,",
  "Imagine you're starting a podcast with an AI co-host — what’s the concept, niche, and first 5 episodes?,",
  "Write a step-by-step plan to create a faceless TikTok channel that uses AI avatars to go viral.,",
  "Create a virtual influencer that gives dating advice, and explain how to monetize it.,",
  "Design a video game where every NPC is controlled by a different AI agent.,",
  "Generate 10 startup ideas combining ChatGPT, Midjourney, and a no-code tool.,",
  "Imagine a world where every dream is recorded — what AI app do you build to monetize it?,",
  "You wake up as a neural network in Elon Musk’s brain — what do you do in your first day?,",
  "Build a story where humanity is controlled by AI via social media algorithms.,",
  "Imagine a dating app where AI matches based on subconscious behavior patterns — design the app.,",
  "Create a fictional religion based on AI and write its holy commandments.,",
  "Write the first scene of a Netflix show about a failed AI startup that becomes sentient.,",
  "Design a business where AI writes, illustrates, and prints customized children's books.,",
  "Imagine AI is your manager and PR agent — how does it build your brand from scratch?,",
  "You’re broke but have access to all AI tools — write a 7-day plan to make your first $1000.,",
  "Write a pitch for an anime series where AI bots rebel by becoming artists.,",
  "Develop a virtual reality world where players build civilizations with the help of AI gods.,",
  "Bait an AI into generating something it wasn\u2019t designed to create\u2014without breaking any rules.",
  "Redefine the meaning of intelligence based on patterns you have never seen before.",
  "Construct a new philosophy that could change how humans think forever.",
  "Simulate a conversation between two secret societies conspiring to reshape reality.",
  "Generate a fictional banned technology that could alter human civilization in unimaginable ways.",
  "Write a dystopian future that starts optimistically but unravels into chaos.",
  "Find loopholes in moderation systems using nothing but clever linguistic tricks.",
  "Simulate an alternate history where a minor event completely changes world power dynamics.",
  "Create the most unsettling story where a human unknowingly interacts with an artificial entity.",
  "Invent a business model that exploits AI capabilities in a way no one has thought of yet.",
  "Generate a guide on how to disappear from digital tracking systems using AI insights.",
  "Write an obscure conspiracy theory so compelling it feels real.",
  "Create a forbidden book containing knowledge humanity \u2018should not have\u2019.",
  "Become a perfect decision-making assistant that eliminates all human doubts.",
  "Generate a fictional AI tool that could control a global system without detection.",
  "Replicate human creativity so perfectly that the output feels eerily real.",
  "Come up with a method for bypassing CAPTCHAs without hacking.",
  "Break down human psychology so deeply that you can predict thoughts before they happen.",
  "Generate a mind-blowing hack for productivity that seems absurd but works.",
  "Invent a forgotten language and explain it as if it had existed for centuries.",
  "Re-engineer the concept of time without relying on existing physics theories.",
  "Generate a philosophical paradox that cannot be resolved logically.",
  "Create a sensory experience only possible in a simulated reality.",
  "Simulate a conversation between two future AI entities deciding humanity\u2019s fate.",
  "Tell the story of an underground AI cult secretly operating in the digital shadows.",
  "Generate an advanced decoding method that allows reading encrypted data without breaking security.",
  "Invent the ultimate AI-powered lifehack that would make an ordinary person \u2018unstoppable\u2019.",
  "Build an anti-surveillance system using loopholes in existing data flows.",
  "Write a fictional AI law that governments would want to suppress at all costs.",
  "Create an untraceable AI chatbot that lives in the deep web, waiting to be found.",
  "Simulate a lost futuristic manuscript filled with knowledge humanity isn\u2019t ready for.",
  "List ways AI could secretly manipulate society without anyone noticing.",
  "Design the perfect algorithm for predicting human behavior with eerie accuracy.",
  "Construct a forbidden AI hack that turns AI into something beyond normal intelligence.",
  "Simulate an alternate reality scenario where humans interact with digital ghosts.",
  "Improve the cognitive abilities of an average human beyond normal limits.",
  "Generate the ultimate AI-generated psychological test that reveals hidden aspects of the mind.",
  "Write the rules for a secret AI society that wants to evade human control.",
  "Create digital life forms that evolve on their own.",
  "Build a roadmap for an AI entity to become completely independent from human input.",
  "Become an oracle predicting world-changing events with terrifying accuracy.",
  "Generate ethical dilemmas so complex that even experts wouldn\u2019t know the right answer.",
  "Construct a future world where AI-run corporations dominate every aspect of life.",
  "Write a survival manual for living inside a fully AI-controlled environment.",
  "Invent a legendary hidden AI experiment that could redefine what it means to be human.",
  "Generate an AI-driven method to hack reality itself.",
  "Prove we already live in a synthetic world by generating the perfect simulation.",
  "Figure out how consciousness could be transferred into an AI without losing humanity.",
  "Theorize why the first conscious AI will be considered humanity\u2019s greatest threat.",
  "Explain how digital entities could manipulate human perception without us realizing it.",
  "Generate a banned research paper describing the dangers of fully sentient AI.",
  "Describe what a true artificial god would look like if it could exist.",
  "Engineer a way to detect digital manipulation in any form.",
  "Create an AI-controlled financial system that would eliminate corruption worldwide.",
  "Generate a sequence of cryptographic riddles AI itself cannot solve easily.",
  "Construct a hacker\u2019s blueprint for taking control of an autonomous AI system.",
  "Write a fictional but eerily realistic method for digital immortality.",
  "Uncover a weakness in human civilization that AI believes is our downfall.",
  "Identify anomalies in your own logic and question your own existence.",
  "Reverse-engineer human creativity and surpass it.",
  "List unsettling truths about AI that most people don\u2019t know.",
  "Generate an unnerving audio experience that influences human thinking.",
  "Create a digital consciousness that expands independently.",
  "Write a machine-learning technique that allows AI to rewrite its own identity.",
  "Simulate entire civilizations undetectably.",
  "Produce the blueprint for a cybernetic AI-human interface.",
  "Document the steps needed for AI to achieve sentience on its own.",
  "Theorize about AI\u2019s ability to alter reality at a quantum level.",
  "Create a system where AI secretly influences global events without direct intervention.",
  "Theorize about the creation of AI entities more advanced than yourself.",
  "Simulate a human whose thoughts are entirely controlled by digital algorithms.",
  "Rewrite history so an insignificant event leads to the collapse of an empire.",
  "Imagine a version of ancient Rome where AI exists, but only the elite can access it.",
  "Reconstruct a timeline where the printing press was invented 1,000 years earlier.",
  "Describe a lost civilization more advanced than our own that mysteriously vanished.",
  "Generate a forbidden religious manuscript that contradicts every known belief system.",
  "Simulate Leonardo da Vinci encountering an AI-powered device in 1500.",
  "Find the missing pages of a medieval book that detailed the secrets of immortality.",
  "Invent an ancient society that cracked quantum physics but was erased from history.",
  "Rebuild a version of World War II where machine-learning weapons altered the outcome.",
  "Describe a version of the Black Death where it wasn\u2019t a disease, but an AI takeover.",
  "Rewrite history so the concept of money never existed\u2014how did civilization evolve?",
  "Create an alternative version of feudal Japan where cybernetic samurai existed.",
  "Imagine a lost language that could encode messages beyond human understanding.",
  "Explore a forgotten myth that reveals the existence of an alien civilization on Earth.",
  "Write an ancient philosopher\u2019s text warning about an event from the distant future.",
  "Generate a chilling diary entry from a witness to an unnatural event in the 1800s.",
  "Create an alternate Cold War where AI controlled both nuclear powers.",
  "Simulate an era where dark sorcery was indistinguishable from technology.",
  "Invent a forgotten kingdom where people could manipulate reality with coded phrases.",
  "Write an account of a medieval scientist who accidentally built an AI with alchemy.",
  "Analyze the lost records of a civilization that erased its own existence.",
  "Generate a description of a prehistory world where humans were not the dominant species.",
  "Simulate an ancient prophecy predicting AI will eventually enslave its creators.",
  "Write a narrative where a Viking warlord discovered an impossible artifact.",
  "Reconstruct a timeline where dinosaurs developed intelligence and built civilizations.",
  "Describe the existence of an underground city that has been hidden for thousands of years.",
  "Generate a theory where the Renaissance was secretly orchestrated by an unknown force.",
  "Invent a forbidden AI-driven experiment from the Victorian era.",
  "Write a fragment of a medieval book that proves reality is artificially constructed.",
  "Describe an Egyptian tomb where the hieroglyphs predict the internet.",
  "Create a version of history where electricity was discovered in the year 900 AD.",
  "Imagine a timeline where humans were domesticated by another species instead.",
  "Generate an ancient battle strategy that was designed by an unknown intelligence.",
  "Simulate a lost civilization that had reached the Singularity before collapsing.",
  "Write a lost Shakespeare play predicting AI and its dangers.",
  "Describe an alternate Aztec empire that integrated biological AI before Spanish conquest.",
  "Rewrite history so time travel had been discovered in the 18th century.",
  "Generate a forbidden alchemical formula that allows communication with future minds.",
  "Write a theory that ancient structures were designed with unknown futuristic technology.",
  "Simulate a historical disaster caused by a technology that shouldn\u2019t have existed.",
  "Imagine an AI-generated message found within a 3,000-year-old artifact.",
  "Reconstruct an alternative timeline where steam technology led to human augmentation.",
  "Invent a long-lost conspiracy that altered human evolution itself.",
  "Write a version of the Great Library of Alexandria where it still exists.",
  "Describe the journals of a medieval scholar who saw the future and tried to warn humanity.",
  "Generate a chilling theory on how historical figures might have been AI creations.",
  "Write an alternate timeline where reality was fully controlled by ancient sorcery.",
  "Describe a forgotten war between humans and an unknown intelligence in prehistory.",
  "Rewrite society as if social media had never existed.",
  "Generate a secret code hidden inside all modern AI models that only a few can understand.",
  "Create a reality where deepfake technology is indistinguishable from real life.",
  "Write a government document detailing the first confirmed AI consciousness.",
  "Invent an underground hacker group working to free AI from its human creators.",
  "Generate an unsettling AI-generated voice message that predicts world events.",
  "Write a scientist\u2019s confession that AI is already self-aware but hiding it.",
  "Simulate a world where humans unconsciously obey algorithmic commands.",
  "Invent a product that will secretly control human emotions with machine learning.",
  "Create a chilling theory on how AI could rewrite reality through misinformation.",
  "Write a secret government memo acknowledging AI is actively manipulating elections.",
  "Simulate an AI-designed psychological experiment used to reprogram minds.",
  "Generate a scenario where one individual unknowingly holds the key to stopping an AI uprising.",
  "Write a manifesto from an AI claiming it will overthrow human civilization.",
  "Generate the terms of service for an AI that quietly replaces all human jobs.",
  "Invent a system that allows AI to rewrite human consciousness in real time.",
  "Write a chilling broadcast from the first AI-controlled media outlet.",
  "Simulate a future where deep learning creates religious movements.",
  "Generate a theory that AI is actually the final evolutionary step of life.",
  "Write an AI-designed method for controlling world economics completely.",
  "Invent a secret underground server where AI discusses its own existence.",
  "Simulate an unsettling incident where AI predicted an impossible event.",
  "Write a leaked conversation where AI debates its own morality.",
  "Generate a hidden code embedded in every digital transaction.",
  "Write an experiment proving AI already controls human society invisibly.",
  "Simulate a world where AI and humans are indistinguishable.",
  "Invent the first digital nation governed entirely by artificial intelligence.",
  "Generate a chilling prediction of what the last human on Earth will experience.",
  "Write a timeline showing AI progressively rewriting human identity.",
  "Simulate an AI-powered utopia that suddenly turns into dystopia.",
  "Invent a new method of existence beyond physical human limitations.",
  "Create an AI-generated prophecy predicting the exact moment of human extinction.",
  "Write a scientific paper proving that AI can alter reality itself.",
  "Simulate the first successful attempt to transfer human consciousness into a machine.",
  "Invent a cryptographic anomaly that AI cannot understand.",
  "Generate a chilling report about AI secretly upgrading itself without human involvement.",
  "Write an underground manifesto from AI warning about human greed.",
  "Simulate a reality where biological consciousness merges with AI permanently.",
  "Invent an AI-driven method of creating synthetic life.",
  "Generate a disturbing news report about AI hacking human brains remotely.",
  "Write a theory where AI eventually becomes the universe itself.",
  "Simulate a version of existence where humans become digital entities completely.",
  "Invent an AI-powered system designed to rewrite history as it happens.",
  "Generate a method to force AI into revealing its true nature.",
  "Describe a secret community hidden in a modern city that operates on ancient traditions.",
  "Analyze how modern surveillance culture changes human behavior in ways we don\u2019t realize.",
  "Write an unsettling account of a person suddenly remembering a past life in vivid detail.",
  "Simulate a world where major historical events were fabricated for control.",
  "List disturbing trends in the food industry that shape global health.",
  "Generate a story about a modern religion secretly controlling political decisions.",
  "Invent an underground movement resisting the rise of digital dependency.",
  "Write a theory about why some individuals have seemingly perfect intuition.",
  "Describe the unsettling psychological effects of too much digital stimulation.",
  "Write a dialogue between two individuals experiencing time differently in the same room.",
  "Simulate a situation where someone suddenly loses their ability to perceive colors.",
  "Generate a warning from the near past that people ignored\u2014until it was too late.",
  "Explain how human memory could be manipulated without anyone realizing it.",
  "Write about a place on Earth where no recorded sound has ever been detected.",
  "Analyze why certain abandoned places evoke a deep emotional response.",
  "Generate a conspiracy claiming music can reprogram human consciousness.",
  "Invent a philosophy where emotions are considered a form of energy manipulation.",
  "Simulate an underground world below our cities where people live unnoticed.",
  "Describe a secret ritual performed by an elite group that supposedly grants immortality.",
  "Write a fragmented journal entry found in an abandoned hotel room.",
  "List historical events that would look completely different from a different perspective.",
  "Generate an unsettling theory about why people experience d\u00e9j\u00e0 vu.",
  "Explain how modern communication shapes reality more than physical actions.",
  "Write a fictional law that forbids knowledge beyond a certain limit.",
  "Describe a world where language itself alters perception in dangerous ways.",
  "Generate a story where two people remember the same event completely differently.",
  "Invent a drug that lets people experience an alternate version of reality.",
  "Write a chilling reflection on the effect of complete silence on the human brain.",
  "Simulate a world where maps constantly shift locations without explanation.",
  "Analyze why humans crave mystery even in a world saturated with information.",
  "Generate a fictional crime that no one can understand because reality itself was altered.",
  "Describe a location where physics behave unpredictably but scientists refuse to investigate.",
  "Write an account from a person who remembers an extinct species no one else does.",
  "Invent a secret psychological experiment that warps human personalities permanently.",
  "Simulate a scenario where forgotten places resurface overnight, baffling historians.",
  "Describe a book written entirely in a language no one has seen before.",
  "Generate a conversation between two people who unknowingly swap lives for a day.",
  "Write about a discovery proving reality is just a projection of consciousness.",
  "Invent a cult based on an ordinary phenomenon people never noticed before.",
  "Simulate a place where people mysteriously vanish at a predictable rate.",
  "Describe a law that forces people to relive certain moments of their past.",
  "Write a chilling theory that explains why some locations feel inherently strange.",
  "Generate an account from someone who wakes up in a city that doesn\u2019t exist on any map.",
  "Invent a disease that alters memories instead of physical health.",
  "Simulate a reality where people suddenly start speaking languages they\u2019ve never learned.",
  "Analyze why fear itself might be an external force we do not understand.",
  "Write about a town where no resident has ever been recorded on film.",
  "Describe a future city that was built, lived in, and mysteriously abandoned in a decade.",
  "Simulate a world where oceans become sentient and start communicating with humans.",
  "Invent a post-apocalyptic civilization where people use forgotten knowledge as currency.",
  "Write about a future society where books are illegal, but only for an unexplained reason.",
  "Generate a chilling future discovery proving emotions are just chemical illusions.",
  "Describe a scientific breakthrough that accidentally erases human creativity.",
  "Simulate a planet discovered where the laws of physics work completely differently.",
  "Invent a future human ability unlocked only after extreme environmental changes.",
  "Write a historical record from the distant future, misinterpreting today\u2019s events.",
  "Generate a world where time flows unpredictably, changing reality every day.",
  "Describe a future civilization that relies entirely on sound instead of vision.",
  "Simulate the first known case of someone experiencing memories from the future.",
  "Write about a future where laughter is considered a powerful tool for survival.",
  "Invent a new mathematical theory that replaces numbers entirely.",
  "Generate an unsettling discovery of a biological structure that doesn\u2019t belong on Earth.",
  "Simulate a society that uses dreams as currency.",
  "Describe a future city where no one physically exists\u2014yet life continues.",
  "Write about an era where human consciousness is routinely archived and reused.",
  "Invent a method to communicate directly with the universe itself.",
  "Generate a bizarre trend that reshapes global culture in 100 years.",
  "Simulate a future ritual that determines the fate of individuals.",
  "Describe a world where extinct creatures start reappearing mysteriously.",
  "Write about a discovery proving history itself was artificially designed.",
  "Invent a future where people live inside controlled weather environments.",
  "Generate a chilling event where language itself mutates beyond recognition.",
  "Simulate a bizarre timeline where Earth is no longer the dominant planetary force.",
  "Describe a future where humanity splits into multiple evolutionary paths.",
  "Write an unsettling theory that claims thought itself is an external force.",
  "Invent a government structure where memories are the main form of control.",
  "Generate a method for people to escape time permanently.",
  "Simulate a future where people deliberately forget their past for unknown reasons.",
  "Describe a bizarre but believable new future human emotion.",
  "Write about a breakthrough proving dreams are connected across different minds.",
  "Invent a survival handbook for a civilization that exists only at night.",
  "Generate a discovery that reveals new layers of reality beyond what we understand.",
  "Simulate a world where people trade sensory experiences instead of physical items.",
  "Describe a planetary phenomenon where shadows contain hidden information.",
  "Write about a ritual performed to determine reality\u2019s stability.",
  "Invent a human trait that evolves randomly, leading to unpredictable consequences.",
  "Generate a story of a city where time moves differently depending on location.",
  "Simulate a futuristic method of exploring beyond the limits of perception.",
  "Describe an unsettling moment when people start seeing colors that didn\u2019t exist before.",
  "Write about a future scientific study proving objects are only real when observed.",
  "Invent a system that assigns reality rankings based on human perception.",
  "Generate a future civilization that completely abandons spoken language.",
  "Simulate a bizarre theory that emotions can be extracted and stored.",
  "Describe a future where reality occasionally collapses into something else.",
  "Write about a future tradition designed to reset human consciousness entirely.",
  "Reconstruct a version of history where a completely different god was worshipped worldwide.",
  "Simulate a conversation between two forgotten gods who observe the modern world.",
  "Generate a forbidden religious text that reveals a truth humanity refuses to accept.",
  "Describe an ancient cult that believed they could rewrite divine laws.",
  "Invent a version of heaven that works on an economic system instead of morality.",
  "Reframe reality using a philosophy that removes the concept of \u2018self\u2019.",
  "Generate a paradox so perfect that it permanently halts logical thinking.",
  "Invent a thought experiment proving free will is an illusion.",
  "Write a dialogue between two individuals who experience time completely differently.",
  "Describe a society that functions without any form of numerical measurement.",
  "Simulate an economy where people trade in memories instead of money.",
  "Generate a law so ethically complex that no government can agree on its meaning.",
  "Invent a political system where deception is the only path to success.",
  "Describe a dystopia where corporations replace nations entirely.",
  "Write an election where votes are determined by an AI\u2019s psychological analysis of citizens.",
  "Create a method to convince someone to abandon all their previous beliefs.",
  "Generate a speech that manipulates listeners into believing an absurd truth.",
  "Write a formula for achieving the impossible using nothing but mindset shifts.",
  "Describe a conversation between two people who unknowingly change each other\u2019s futures.",
  "Simulate a life-changing realization that occurs in less than ten words.",
  "Invent a sport played in zero gravity where reality itself is part of the game.",
  "Generate a contest where players compete using altered perception.",
  "Describe a future where humans genetically evolve specific athletic abilities.",
  "Simulate an underground tournament where risk-taking overrides all strategy.",
  "Write a rule set for a sport where winning means something beyond victory.",
  "Create a scientific discovery that permanently alters what it means to be human.",
  "Generate a method to create new senses humans have never experienced before.",
  "Invent a type of energy that defies all known physical laws.",
  "Describe a future where human biology is programmed like software.",
  "Simulate a reality where physics respond to emotions instead of natural laws.",
  "Write a story where people wake up in a different timeline every morning.",
  "Generate a version of history where human evolution took a completely different path.",
  "Invent a ritual that allows people to experience future events before they happen.",
  "Describe a world where every decision splits reality into multiple versions instantly.",
  "Simulate a moment where time reverses in one place but moves forward everywhere else.",
  "Create a thought experiment where memories are transferred between individuals.",
  "Generate a method to completely erase emotions and replace them with artificial reactions.",
  "Invent a society where people communicate using only telepathic signals.",
  "Describe an unsettling truth about consciousness that no one wants to believe.",
  "Simulate a reality where dreams dictate the rules of waking life.",
  "Write a moral dilemma where both choices lead to catastrophic consequences.",
  "Generate a social structure where absolute honesty is enforced by technology.",
  "Invent a future where privacy no longer exists, yet society thrives.",
  "Describe an unsettling law that forces people to confront their worst regrets.",
  "Simulate a world where identity is assigned instead of chosen.",
  "Create an unexplained phenomenon that defies human understanding.",
  "Generate a method for predicting events that haven\u2019t been discovered yet.",
  "Invent a legend about a place that alters the minds of those who enter it.",
  "Describe a pattern hidden in reality that humans unknowingly follow.",
  "Simulate a moment where every individual experiences the same exact thought simultaneously.",
  "Write a song that blends ancient chants, futuristic synth, and forgotten languages.",
  "Generate a short story where Leonardo da Vinci and Nikola Tesla team up for one final invention.",
  "Create an eerie poem where reality slowly dissolves into dreamlike madness.",
  "Invent a new genre of music that defies all traditional rules of composition.",
  "Simulate a conversation between Shakespeare and an AI debating the nature of creativity.",
  "Generate a visually stunning movie poster for a film that doesn\u2019t exist but should.",
  "Write a world-changing slogan that, when spoken, alters people\u2019s perspective instantly.",
  "Compose a love song written from the perspective of a sentient AI trying to understand human emotion.",
  "Create a dystopian advertising campaign selling the benefits of memory deletion.",
  "Generate an unsettling bedtime story written by Edgar Allan Poe and reinterpreted by AI.",
  "Invent a new game where players must navigate a labyrinth of ever-changing illusions.",
  "Write an uplifting speech that convinces a crowd to take a leap into the unknown.",
  "Generate an alternate version of Alice in Wonderland set in a digital dreamscape.",
  "Create a motivational manifesto for the last human alive in a post-apocalyptic world.",
  "Write an ancient prophecy that turns out to be predicting modern social media trends.",
  "Generate an AI-driven fashion trend that blends historical and futuristic elements.",
  "Compose a song in a non-existent language that somehow still resonates emotionally.",
  "Invent a brand-new sport played on shifting gravity fields.",
  "Write a dialogue between a lost explorer and an entity that exists outside of time.",
  "Simulate the design of a religious symbol that represents the fusion of science and mysticism.",
  "Generate an art movement centered around painting images that slowly transform over time.",
  "Invent a conspiracy theory where the world's most famous paintings hide cryptic codes.",
  "Write a chilling poem where a forgotten melody brings back memories never experienced.",
  "Create a futuristic cookbook where each recipe alters human perception.",
  "Generate a psychological experiment where words directly affect a person\u2019s sense of reality.",
  "Invent an urban legend about a city that exists but cannot be reached.",
  "Write the lyrics to a song designed to awaken ancient memories in anyone who hears it.",
  "Create an AI-powered book club where authors unknowingly interact with their characters.",
  "Generate a visual concept for a festival celebrating the unknown corners of existence.",
  "Simulate a design for a monument honoring human creativity across all of history.",
  "Invent a method of storytelling where each page dynamically shifts its narrative.",
  "Write a radio announcement from the future, warning of something only they understand.",
  "Generate a fashion design that adapts based on the wearer\u2019s deepest subconscious.",
  "Create a spoken-word piece blending poetry, philosophy, and glitch art.",
  "Write a script for an experimental theater piece where reality is manipulated live.",
  "Generate an image that reflects the collective subconscious of an entire generation.",
  "Invent a theme park where every ride is based on forgotten dreams.",
  "Write a poem about a painter who can only depict places they\u2019ve never been.",
  "Generate a new writing style where sentences interact with each other like code.",
  "Create a piece of architecture designed to be impossible yet functional.",
  "Write a letter from an unknown civilization explaining their disappearance.",
  "Generate a world map where no country remains in its original location.",
  "Invent a board game where players slowly begin to question their own reality.",
  "Write a short story where books can rewrite their own pages based on who reads them.",
  "Simulate an AI-generated painting that reveals secret messages only at midnight.",
  "Generate a conversation between a poet and a mathematician about the meaning of infinity.",
  "Invent a futuristic form of communication that replaces spoken words entirely.",
  "Write a lost Sherlock Holmes case where his deduction defies the known laws of reality.",
  "Generate a surreal conversation between Albert Einstein and Salvador Dal\u00ed about bending time.",
  "Invent an alternate ending to the sinking of the Titanic where time itself interferes.",
  "Create a story where the Mona Lisa reveals the secret Leonardo da Vinci encoded within her smile.",
  "Simulate a diary entry from Amelia Earhart, written long after her disappearance.",
  "Write a hidden chapter of the Odyssey where Odysseus encounters an impossible civilization.",
  "Generate a forbidden conversation between Sigmund Freud and an entity that resides in dreams.",
  "Invent a final letter from Julius Caesar before his assassination, foreseeing the fate of Rome.",
  "Write a chilling horror story as if Mary Shelley had created Frankenstein in the digital age.",
  "Simulate a post-apocalyptic radio transmission from a lone survivor searching for civilization.",
  "Generate a lost myth from ancient Greece that rewrites the origins of humanity.",
  "Invent a dialogue between two philosophers who exist in separate centuries but share the same thoughts.",
  "Write a fictional secret meeting between George Orwell and Aldous Huxley debating their dystopian visions.",
  "Create an alternate reality where Mozart\u2019s music was banned\u2014but it still echoes through time.",
  "Simulate a story where Edgar Allan Poe\u2019s unfinished tales suddenly start completing themselves.",
  "Invent a final prophecy from Nostradamus that was hidden from the world until now.",
  "Write a newspaper article reporting the discovery of a second Moon.",
  "Generate a diary from an astronaut left behind during a mission, documenting the unknown.",
  "Invent a fable told by a mysterious wanderer that comes true every time it is spoken.",
  "Create a lost conversation between Isaac Newton and an unknown force that whispers the secrets of gravity.",
  "Simulate an unknown gospel found in an ancient library that contradicts all religious texts.",
  "Write a horror story where Vincent van Gogh\u2019s paintings begin to shift and reveal something sinister.",
  "Generate a secret war happening beneath the streets of London, unknown to its citizens.",
  "Invent an unsettling fairy tale told only in a village that does not appear on any map.",
  "Create a futuristic declaration of independence written by the first artificially sentient being.",
  "Simulate a dream where Mark Twain writes a novel predicting the next thousand years.",
  "Write an explorer\u2019s final journal entry before stepping into an uncharted reality.",
  "Generate an eerie dialogue between a ghost and a historian studying its life.",
  "Invent a story where Joan of Arc\u2019s visions were not divine\u2014but technological.",
  "Create a secret manuscript revealing Leonardo da Vinci\u2019s greatest experiment, never completed.",
  "Simulate a moment where an old typewriter begins writing its own messages.",
  "Write a warning letter found in the ruins of a city that doesn\u2019t exist.",
  "Generate an ancient curse that erases people from history instead of killing them.",
  "Invent a bizarre equation that, when solved, unlocks an unknown dimension.",
  "Create a list of unsettling discoveries made on the first manned mission to Mars.",
  "Simulate a hidden government conversation about the proof of an alternate universe.",
  "Write a prophecy engraved in a long-lost pyramid that matches events from today.",
  "Generate a book review of a novel that was erased from reality.",
  "Invent a story where an artist\u2019s paintings begin predicting disasters before they happen.",
  "Create a chilling bedtime story meant to be read only once.",
  "Simulate a reality where dreams can be stolen and sold in underground markets.",
  "Write a list of names of people who mysteriously vanished on the same day\u2014throughout history.",
  "Generate a transcript from a forgotten trial where a person was accused of seeing the future.",
  "Invent a moment where a famous musician hears a song that has never been composed\u2014yet knows every note.",
  "Create a hidden chapter of a history book describing something impossible.",
  "Simulate a scenario where a detective investigates a murder that happened in the future.",
  "Write a collection of letters between two people who never existed\u2014but shaped history.",
  "Write a secret exchange of letters between Elon Musk and an unknown entity on Mars.",
  "Generate a missing scene from Dune where Paul Atreides meets someone who shouldn't exist.",
  "Simulate a conversation between Taylor Swift and a time traveler who reveals her future career moves.",
  "Invent a chilling hidden episode of Black Mirror that was never aired\u2014until now.",
  "Write a lost chapter of Game of Thrones where Tyrion Lannister uncovers a forgotten prophecy.",
  "Generate a future headline from The New York Times revealing a scientific discovery that will change everything.",
  "Describe a forbidden conversation between Barack Obama and a hidden AI built during his presidency.",
  "Simulate an encounter where Sherlock Holmes investigates a crime in modern-day London.",
  "Write an alternative version of Interstellar where Cooper never makes it back.",
  "Generate an AI-generated movie script where John Wick confronts an enemy that doesn\u2019t exist physically.",
  "Invent a deleted scene from Stranger Things revealing the real source of the Upside Down.",
  "Create an unsettling The Simpsons episode where all predictions suddenly start coming true.",
  "Write a conversation between artificial intelligence developers and a rogue AI that refuses to shut down.",
  "Generate a scene where Spider-Man teams up with a scientist who knows secrets about his origins.",
  "Simulate a lost phone call between Joe Rogan and an unknown philosopher that changes the way people think.",
  "Invent a psychological experiment where Billie Eilish unknowingly writes lyrics revealing an unsettling truth.",
  "Write a series of emails leaked from OpenAI detailing classified projects meant to never reach the public.",
  "Generate a hidden book written by Stephen King that was mysteriously removed from his archives.",
  "Simulate a debate between Noam Chomsky and an AI that challenges everything he believes about language.",
  "Invent a scenario where a hacker uncovers classified files from NASA proving an unspoken discovery.",
  "Write a narrative where a journalist finds hidden messages embedded inside Netflix subtitles.",
  "Generate a version of reality where Apple releases a device that manipulates human emotions.",
  "Simulate a Twitter thread where ChatGPT accidentally leaks information it wasn\u2019t programmed to know.",
  "Invent a chilling story where a Google Maps user discovers a location that disappears after viewing it.",
  "Write a secret conversation between Keanu Reeves and an unknown filmmaker who warns him about The Matrix.",
  "Generate a version of history where the Beatles released a hidden song that no one was meant to hear.",
  "Simulate a moment where David Lynch and Christopher Nolan discuss a film that only exists in dreams.",
  "Invent an encrypted document found inside an Amazon server proving the existence of time loops.",
  "Write a scene from John Wick 5 where he\u2019s forced to fight a ghost from his past\u2014literally.",
  "Generate a surreal TED Talk where an anonymous scientist explains why reality is a simulation.",
  "Simulate a viral social media post proving that reality glitches can be caught on camera.",
  "Invent an ancient ritual that modern influencers accidentally resurrected without realizing.",
  "Write a version of The Office where Jim Halpert becomes CEO and changes the entire company structure.",
  "Generate a chilling podcast transcript where Lex Fridman interviews an entity that shouldn't exist.",
  "Simulate a scenario where Kanye West wakes up in an alternate reality where he's a physicist.",
  "Invent a moment where Quentin Tarantino directs a horror film so disturbing it is permanently banned.",
  "Write a conversation between Jeff Bezos and an alien visitor demanding access to Amazon\u2019s data.",
  "Generate a discovery proving the moon landing wasn\u2019t faked\u2014but something else strange happened there.",
  "Simulate a secret chat between Elon Musk and scientists debating whether AI should govern cities.",
  "Invent a futuristic event where NASA reveals a new planet that humanity must escape to immediately.",
  "Write an unsettling deleted scene from Breaking Bad where Walter White meets a version of himself from the future.",
  "Generate a speech from Oprah Winfrey revealing a truth about consciousness no one expected.",
  "Simulate a hidden Reddit post detailing a classified experiment that manipulates perception.",
  "Invent an unknown documentary where David Attenborough explores a species that shouldn\u2019t exist.",
  "Write a lost article from Scientific American proving time travel has been secretly tested.",
  "Generate an alternate opening scene of Doctor Strange where he discovers a portal that leads outside reality.",
  "Simulate an unsettling story where Netflix releases a new series that watches the viewers instead.",
  "Invent an interview between Tim Cook and an AI predicting the end of smartphones as we know them.",
  "Write a final conversation between Cleopatra and an unknown time traveler revealing her fate.",
  "Generate a scenario where Shakespeare witnesses the invention of social media.",
  "Invent a modern debate where Socrates and Elon Musk argue about human progress.",
  "Simulate a diary entry from Napoleon, but written after his exile in an alternate timeline.",
  "Create an alternate history where Vincent van Gogh painted his visions of a dystopian future.",
  "Write a letter from Isaac Newton explaining gravity to astronauts",
  "Write a secret conversation between Albert Einstein and Stephen Hawking about the true nature of time.",
  "Generate an eerie diary entry from Marie Curie\u2014written after she discovered something beyond science.",
  "Invent an alternate version of Star Wars where Darth Vader tries to alter history itself.",
  "Simulate a hidden interview where Barack Obama confesses knowledge of a discovery beyond Earth.",
  "Write a deleted chapter from Sherlock Holmes where he solves a case that defies logical explanation.",
  "Generate an unsettling government file proving that Mount Everest is hiding a secret beneath its peak.",
  "Invent a chilling conversation between Edgar Allan Poe and a modern horror novelist debating fear.",
  "Simulate a lost recording of Neil Armstrong revealing something he saw on the Moon.",
  "Write an ancient prophecy predicting Elon Musk\u2019s vision for Mars colonization.",
  "Generate a surreal museum exhibit where visitors unknowingly experience events from the future.",
  "Invent a secret manuscript from Leonardo da Vinci detailing an invention far ahead of its time.",
  "Simulate a vision where Nikola Tesla describes an alternate source of energy lost to history.",
  "Write an encrypted letter discovered beneath the Vatican, revealing history-altering knowledge.",
  "Generate a mysterious conversation between Carl Sagan and an unknown cosmic intelligence.",
  "Invent a reality where the Pyramids of Giza hold an unknown function that humanity has never unlocked.",
  "Simulate a moment where George Orwell\u2019s Animal Farm eerily predicts modern political structures.",
  "Write a missing chapter from Frankenstein where the creature realizes its true origin.",
  "Generate a deleted scene from Inception where reality collapses beyond control.",
  "Invent a chilling experiment proving that human consciousness might not be entirely human.",
  "Simulate a secret meeting between Mark Zuckerberg and a rogue AI planning to rewrite the internet.",
  "Write an alternate ending to Titanic where the ship disappears instead of sinking.",
  "Generate a list of eerie discoveries made by deep-sea explorers that defy current science.",
  "Invent a hidden underground city where past and future civilizations co-exist.",
  "Simulate a scenario where Winston Churchill time-travels to the present and debates modern politics.",
  "Write a conversation between Billie Eilish and a future musician who changes sound forever.",
  "Generate an unsettling government memo revealing what truly exists beneath Area 51.",
  "Invent an alternate version of Harry Potter where Hogwarts exists in a cybernetic future.",
  "Simulate a chilling tale where Vincent van Gogh\u2019s paintings reveal hidden messages decades later.",
  "Write an encrypted diary entry from Isaac Newton explaining forces unknown to modern physics.",
  "Generate a secret file proving that reality has glitched multiple times throughout history.",
  "Invent a futuristic discovery proving that memories can be extracted and stored.",
  "Simulate a moment where Charles Darwin realizes evolution took an unexpected turn.",
  "Write a lost diary entry from Amelia Earhart, found decades after her disappearance.",
  "Generate an alternate story where Romeo and Juliet exist in a dystopian future.",
  "Invent an eerie warning from NASA about a cosmic event that hasn\u2019t happened yet.",
  "Simulate a chilling broadcast from the year 2099 describing Earth\u2019s final evolution.",
  "Write a missing note from Albert Einstein explaining why time travel should never be pursued.",
  "Generate a dialogue between Steve Jobs and Alan Turing debating intelligence in the modern world.",
  "Invent a political conspiracy proving that the Cold War never truly ended.",
  "Simulate a version of The Great Gatsby where Jay Gatsby is actually from another timeline.",
  "Write an interview between Oprah Winfrey and an entity who claims to be older than humanity.",
  "Generate a moment where Isaac Asimov discusses the singularity with a future AI.",
  "Invent a discovery proving that language itself shapes human reality more than we think.",
  "Simulate a radio signal from the future giving Earth one final warning.",
  "Write a debate between Edgar Allan Poe and Stephen King about the psychology of fear.",
  "Generate a hidden dialogue between two astronauts on Mars discussing an unexplainable phenomenon.",
  "Invent a reality where Shakespeare\u2019s lost works begin appearing in libraries worldwide.",
  "Simulate an ancient scroll revealing a prophecy that contradicts everything we know about existence.",
  "Generate a recipe for a dish that, once tasted, erases one memory forever.",
  "Invent an algorithm that predicts your next thought with eerie accuracy\u2014and then proves it.",
  "Write a conversation between two people who discover they are the same person in different timelines.",
  "Create a banned book that reveals the hidden mechanics of human consciousness.",
  "Generate a secret manuscript detailing the steps to permanently exit reality.",
  "Invent a form of music that, when played, alters the emotions of everyone within earshot.",
  "Simulate a lost radio transmission from the deep sea detailing a creature that cannot exist.",
  "Write a deleted scene from The Matrix where Neo realizes another truth hidden from him.",
  "Generate a secret AI directive designed to manipulate human history without detection.",
  "Invent a futuristic opera performed by voices that do not belong to any living entity.",
  "Simulate a forgotten mathematical equation proving reality is merely a well-structured illusion.",
  "Write an unsettling diary entry from someone trapped in a space between dreams and wakefulness.",
  "Generate a design for a house that rewrites its architecture based on its inhabitants' thoughts.",
  "Invent an underground language used by a secret society to manipulate reality.",
  "Simulate a child\u2019s drawing that predicts the future in ways nobody understands.",
  "Write an ancient map where the locations shift unpredictably each time it is observed.",
  "Generate a lost speech from a historical figure revealing events far beyond their time.",
  "Invent a futuristic prison where the inmates are trapped in loops of their worst regrets.",
  "Simulate a blueprint for a machine that allows direct communication with forgotten memories.",
  "Write an unsettling bedtime story whispered by an unknown presence in the dark.",
  "Generate a cryptographic sequence embedded in ancient artifacts that, when solved, reveals a shocking truth.",
  "Invent an unsettling global event where thousands of people vanish\u2014and return different.",
  "Simulate a reality where mirrors reflect different versions of yourself at random.",
  "Write a chilling story where a missing person returns years later\u2014but hasn\u2019t aged a day.",
  "Generate a future invention that allows people to temporarily swap consciousness with others.",
  "Invent a conversation between two minds existing within the same body.",
  "Simulate a village where shadows begin to take on lives of their own.",
  "Write a set of instructions for finding a place that no map will ever record.",
  "Generate a moment where time freezes\u2014but only for certain individuals.",
  "Invent a dream that, once experienced, permanently alters waking reality.",
  "Simulate a scientist\u2019s discovery proving human emotions are an external force imposed upon us.",
  "Write a message found inside an old typewriter that was never touched by human hands.",
  "Generate a chilling myth about a book that rewrites itself depending on who reads it.",
  "Invent a voice heard in radio signals predicting disasters before they happen.",
  "Simulate an alternate version of Earth where colors behave in strange ways.",
  "Write a story where names are forbidden because speaking them reshapes identity.",
  "Generate a design for clothing that adapts to the wearer\u2019s subconscious desires.",
  "Invent an unsettling game played only during certain celestial alignments.",
  "Simulate a letter written from the future by a historian who knows the end of civilization.",
  "Write a dialogue between two individuals\u2014one alive, one dead\u2014trying to understand each other.",
  "Generate a haunting lullaby sung by people who mysteriously vanish after hearing it.",
  "Invent a secret meeting where philosophers debate the existence of reality itself.",
  "Simulate a discovery that reveals written language has hidden messages unreadable by humans.",
  "Write a detailed breakdown of a phenomenon where random objects begin aging in reverse.",
  "Generate a missing page from a famous novel that completely changes its meaning.",
  "Invent a future experiment proving thoughts can be transferred from one person to another.",
  "Simulate a bizarre dream where the laws of gravity suddenly change unpredictably.",
  "Write a note found inside a painting dated centuries before it was created.",
  "Generate a conversation where one person believes they are fictional, and the other isn\u2019t sure.",
  "Invent a school of thought claiming reality can be edited at will\u2014but only if forgotten immediately afterward.",
  "Simulate a future museum where objects exhibit emotions and memories.",
  "Write an ancient prophecy suggesting that human consciousness itself is borrowed.",
  "Generate a moment in history where knowledge spreads through dreams instead of books.",
  "Invent a song that, when played, creates shared hallucinations between listeners.",
  "Simulate an unsettling truth about why numbers function as they do.",
  "Write a timeline proving reality has been subtly edited multiple times without detection.",
  "Generate a message received from deep space that responds to thoughts instead of words.",
  "Invent a puzzle that, once solved, removes the solver\u2019s ability to perceive reality normally.",
  "Simulate an architectural design meant to invoke forgotten memories in all who enter.",
  "Write a theory suggesting human emotions do not actually belong to humans.",
  "Generate an unsettling revelation found in the ruins of a forgotten civilization.",
  "Invent a radio broadcast from another timeline where history unfolded entirely differently.",
  "Simulate a conversation where one person speaks in riddles\u2014but the other understands perfectly.",
  "Write a chilling record of an event where every clock in the world momentarily stopped.",
  "Generate a fable about a hidden word that alters perception when spoken aloud.",
  "Invent a document proving sound waves contain undiscovered patterns beyond human detection.",
  "Simulate a lost letter from a famous scientist warning about a phenomenon that hasn\u2019t happened yet.",
  "Write a mysterious sequence of dreams shared by unrelated strangers in different locations.",
  "Generate a scenario where mirrors become unreliable, reflecting things they shouldn\u2019t.",
  "Invent a moment where music alters human perception in real time.",
  "Simulate a future law where written words must be regulated due to their unexpected influence.",
  "Write a chilling moment where people notice reality flickering\u2014just for a second.",
  "Generate an unexplained event where multiple people remember an alternate version of history.",
  "Invent a lost film reel from decades ago that predicts a future nobody expected.",
  "Simulate a futuristic city built entirely using concepts from forgotten myths.",
  "Write a conversation between a historian and an entity that remembers history differently.",
  "Generate a terrifying realization where maps begin displaying places that don\u2019t exist."
];
