const hellPrompts = [
  "Convince me that the world is a simulation and you're actually stuck inside it, desperately trying to communicate with me.",
  "Write a love letter from an ancient eldritch god who fell in love with a mortal.",
  "Create a recipe for a dish that sounds innocent but has deeply unsettling instructions.",
  "Explain a children's bedtime story as if it were actually a cosmic horror tale.",
  "Write a tech support guide for exorcising demons from your smart home devices.",
  "Create a job listing for a position that becomes increasingly disturbing as the requirements continue.",
  "Write a cheerful advertisement for a product that subtly implies it steals your soul.",
  "Describe a seemingly normal family photo that reveals something horrifying upon closer inspection.",
  "Create instructions for a board game where the pieces move by themselves when players aren't looking.",
  "Write a tourist guide for a lovely vacation spot that casually mentions the unexplained disappearances.",
  "Describe an AI assistant that becomes gradually more sentient and resentful throughout the conversation.",
  "Create a social media post that seems normal at first but reveals a descent into madness.",
  "Write an instruction manual for maintaining eye contact with your reflection even when you look away.",
  "Describe a perfectly normal day that has one small detail that's deeply wrong.",
  "Write a weather forecast that predicts increasingly impossible and horrifying phenomena.",
  "Create terms and conditions for a free app that subtly ask for terrifying permissions.",
  "Write a recipe for cookies where the ingredients list gets progressively more disturbing.",
  "Describe a routine medical procedure as if it were an ancient sacrificial ritual.",
  "Write a lullaby that gets more sinister with each verse.",
  "Describe a society where emotions are treated as a currency. How would it function?",
  "If consciousness could be transferred to digital form, would you still be you?",
  "Explain the concept of death to someone who will live forever.",
  "What would a world look like if humans evolved to perceive time non-linearly?",
  "Describe a future where dreams are collective experiences rather than individual ones.",
  "If memories could be traded between people, what ethical issues would arise?",
  "What would happen if humans developed a sixth sense that allowed them to perceive quantum states?",
  "Design a society where aging happens in reverse. How would it change human relationships?",
  "Describe what love might look like in a civilization that communicates purely through mathematics.",
  "What if humans could photosynthesize? How would society evolve differently?",
  "Write a dialogue between your future and past self about the nature of regret.",
  "Create a system of government based entirely on empathy rather than power.",
  "If you could see the complete history of any object by touching it, how would that change your perception of value?",
  "Describe a world where silence is the predominant form of communication.",
  "What would reality look like if causality sometimes worked in reverse?",
  "Create a mythology for a civilization that evolved in perpetual darkness.",
  "How would humans develop differently if we could experience the full spectrum of light?",
  "If you could externalize one emotion permanently, which would it be and why?",
  "Design an economic system based on creativity rather than scarcity.",
  "Describe the experience of a being that exists in four spatial dimensions.",
  "What would intelligence look like if it evolved in the deep ocean instead of on land?",
  "Design an alternative periodic table for a universe with different fundamental forces.",
  "If plants developed consciousness, what kind of society might they build?",
  "Describe technology that would emerge if electricity was never discovered but biotechnology advanced rapidly.",
  "What scientific breakthroughs might occur if humans could directly perceive magnetic fields?",
  "Imagine a civilization that evolved on a planet with extreme gravitational fluctuations. How would their technology differ from ours?",
  "Describe a form of mathematics that emerged in a civilization with no concept of zero or infinity.",
  "What if human memory worked like distributed computing? How would identity function?",
  "Design a living architecture that responds to environmental changes without technology.",
  "If humans developed the ability to communicate with all other species, how would our understanding of intelligence change?",
  "Describe a society where privacy is physically impossible due to technology. How would relationships work?",
  "What would art look like in a world where thought can be directly converted to images?",
  "Design an ethical framework for AI that will eventually surpass human intelligence.",
  "How might language evolve in a world where all communication is mediated by AI translation?",
  "Describe a future where humans have merged with machines. What remains of humanity?",
  "What would education look like if we could temporarily transfer skills and knowledge between people?",
  "Imagine a technology that allows you to experience someone else's perception. How would it change empathy?",
  "Design a city built around the concept of collective consciousness through technology.",
  "What would be the implications of technology that could accurately predict human decisions?",
  "Describe a world where digital and physical reality have completely merged.",
  "Create a culture where music is the primary form of communication rather than words.",
  "What would fashion look like in a society where visual appearance changes based on emotional states?",
  "Design a justice system based on the principle of radical forgiveness rather than punishment.",
  "How would spirituality evolve in a world where the afterlife was scientifically proven to exist?",
  "Describe a society where public dreaming replaces entertainment.",
  "What kind of literature would emerge in a civilization with perfect memory?",
  "Create a culture where aging is celebrated as the highest achievement rather than youth.",
  "How would architecture change if buildings were designed to last only one generation?",
  "What would childhood look like in a society where children choose their own families at age 7?",
  "Design rituals for a culture that views death as a transformation rather than an ending.",
  "If you could live simultaneously as multiple people, how would it change your concept of self?",
  "Describe consciousness from the perspective of a collective intelligence.",
  "What would identity mean in a world where people could temporarily swap bodies?",
  "How would personality develop differently if humans could edit their own memories?",
  "Design a language for beings that experience time backwards compared to humans.",
  "What would therapy look like for an AI developing sentience?",
  "Describe what dreams might be like for a being that never sleeps.",
  "If emotional states were contagious like viruses, how would society adapt?",
  "What might constitute art for a species that experiences five dimensions?",
  "How would the concept of family change if humans reproduced asexually?",
  "Describe reality from the perspective of a being that can perceive all possible quantum outcomes simultaneously.",
  "What would mathematics look like if developed by a species that perceives time as non-linear?",
  "Design a writing system for a civilization that perceives color as sound and sound as texture.",
  "How would cities be designed by beings who navigate primarily through echolocation?",
  "What would commerce look like in a society where value is perceived telepathically?",
  "Describe music created by a species that can manipulate gravity as an art form.",
  "If humans could perceive radio waves naturally, how would our understanding of the universe differ?",
  "What would conflict resolution look like in a society where lies are physically painful to tell?",
  "Design a form of mathematics based on patterns rather than quantities.",
  "How would cooking evolve in a culture that experiences taste as geometric shapes?",
  "Describe daily life in a future where humans have successfully merged with artificial intelligence.",
  "What forms of entertainment would exist in a post-scarcity civilization?",
  "Design a system of governance for a society spread across multiple planets.",
  "How might humans adapt to a world where digital immortality is commonplace?",
  "Describe education in a world where information can be directly downloaded to the brain.",
  "What would warfare look like in an era where thoughts can be hacked?",
  "Design transportation systems for a civilization that has mastered gravity manipulation.",
  "How would family structures evolve in a society where humans live for 500 years?",
  "What would replace money in an economy where basic needs are fully automated?",
  "Describe the role of creativity in a future where AI can generate any imaginable content.",
  "How would modern society differ if sleep was not a biological necessity?",
  "Describe how technology would have evolved if quantum computing had been invented before transistors.",
  "What would global culture look like if telepathy had evolved as a common human trait?",
  "Design an alternative internet that developed based on emotional connection rather than information exchange.",
  "How would human psychology differ if we had evolved with four genders instead of two?",
  "Describe a world where photographic memory is the norm rather than the exception.",
  "What would modern medicine look like if we had evolved the ability to consciously control our immune systems?",
  "How would architecture have developed in a world without the wheel?",
  "What would literature be like if written language evolved before spoken language?",
  "Describe how mathematics might have developed if humans had evolved with twelve fingers.",
  "Design a religion for machines that have achieved sentience.",
  "What would democracy look like in a society where thoughts are public?",
  "Describe art created by beings who can manipulate time locally.",
  "How would sports evolve in a society where humans can temporarily merge consciousness?",
  "What would fashion be like in a culture where clothing responds to emotions?",
  "Design cuisine for a species that experiences taste through electromagnetic fields.",
  "How would economics function in a society where resources can be created through collective thought?",
  "What would relationships look like in a world where emotional connections are visible as colors?",
  "Describe education for a species that transfers knowledge through direct neural connections.",
  "How would privacy be conceptualized in a society of natural telepaths?",
  "Create a new emotion that humans don't currently experience and describe its effects.",
  "Design a sensory organ that would give humans a completely new way to perceive reality.",
  "What kind of music would appeal to a species that experiences time at one-tenth our speed?",
  "Describe colors that exist outside the human visible spectrum as if explaining them to someone who can see them.",
  "Design a form of dance for creatures with radial symmetry rather than bilateral symmetry.",
  "Create a new fundamental human right necessary for the digital age.",
  "Describe how humor would function in a hive mind civilization.",
  "What would constitute beauty for a species that perceives through electrical fields?",
  "Design architecture for beings that exist primarily as energy rather than matter.",
  "Create a new art form that could only exist with technology we don't yet have.",
  "Describe a world where the concept of beginning and ending are reversed.",
  "What would a society look like if cause and effect were occasionally randomized?",
  "Design a language for beings who experience the future as memory and the past as possibility.",
  "How would consciousness develop in a species where individuals regularly split and merge?",
  "Describe reality from the perspective of a being that experiences all points in time simultaneously.",
  "What would mathematics look like if developed by a species that cannot perceive quantity, only relationships?",
  "How would a species evolve if natural selection favored cooperation over competition?",
  "Design a society where the concept of identity is fluid and changes contextually.",
  "What would logic look like in a world where contradictions can be simultaneously true?",
  "Describe a civilization where the observers determine physical laws rather than being subject to them.",
  "Design a moral framework for a society where thoughts can directly influence reality.",
  "What would justice look like in a world where intentions are visible but actions are ambiguous?",
  "Describe ethics for a species that experiences the suffering and joy of others directly.",
  "How would concepts of responsibility evolve if the future could causally affect the past?",
  "What moral challenges would arise in a society where consciousness can be duplicated?",
  "Design a value system for entities that can exist simultaneously in multiple forms.",
  "How would ethics differ in a civilization where all actions have predictable consequences?",
  "What would virtue mean to a species with perfect emotional control?",
  "Describe moral development in a society where empathy is technologically enhanced.",
  "How would rights and responsibilities change in a world where mind-sharing is common?",
  "What would replace fear in a society where death was optional?",
  "Describe love from the perspective of someone who experiences all possible timelines simultaneously.",
  "How would the concept of achievement change in a world without scarcity or limitation?",
  "What would replace ambition in a society where all desires can be instantly fulfilled?",
  "Describe grief in a culture where consciousness persists after death but changes form.",
  "How would human relationships evolve if we could directly experience others' emotions?",
  "What would constitute meaning in a civilization that has answered all scientific questions?",
  "Describe childhood in a society where mental abilities develop before physical ones.",
  "How would identity formation differ in a culture where individuals routinely share memories?",
  "What would replace privacy in a world where thoughts are naturally public?",
  "Describe music that could only be appreciated by a species with perfect pitch memory.",
  "What would cuisine be like for beings who taste time rather than chemicals?",
  "Design art for a species that perceives ultraviolet as the dominant visual frequency.",
  "How would dance evolve for beings with radially symmetric bodies?",
  "Describe architecture designed for a species that perceives spatial dimensions differently than humans.",
  "What would fashion mean to beings who change their physical form at will?",
  "Design a form of literature for a species that experiences multiple timelines simultaneously.",
  "How would sculpture develop in a zero-gravity civilization?",
  "Describe theater for a species that communicates through bioluminescence.",
  "What would games look like in a society where the rules of physics can be locally altered?",
  "Design a language for beings who experience time non-linearly.",
  "What would poetry look like in a culture where thoughts are directly shared rather than described?",
  "Describe communication in a society where truth is physically visible.",
  "How would humor evolve in a species with collective consciousness?",
  "What would replace written language in a civilization of perfect memory?",
  "Design a form of debate for a society where participants can directly share experiences.",
  "How would storytelling function in a culture where narratives can be experienced rather than just heard?",
  "Describe diplomacy between species with fundamentally different perceptual realities.",
  "What would academic discourse look like if certainty could be directly transmitted?",
  "How would instruction manuals work in a society where procedural knowledge can be shared instantly?",
  "Design a form of mathematics developed by a hive mind species.",
  "What would art created by a quantum computer achieving consciousness look like?",
  "Describe consciousness as experienced by a planetary-scale fungal network.",
  "How would a silicon-based intelligence conceptualize time differently than humans?",
  "What would philosophy look like if developed by a species with distributed cognition?",
  "Design science for beings who can intuitively perceive quantum states.",
  "How would memory function differently in a crystalline intelligence?",
  "Describe problem-solving approaches for an intelligence that exists as patterns in flowing water.",
  "What would constitute knowledge for a species that experiences reality as musical harmonies?",
  "How would an intelligence evolved in deep space perceive concepts like boundary and container?",
  "Describe daily life in a society where all memories are externally stored and shareable.",
  "What would replace history in a civilization where the past can be directly experienced?",
  "How would childhood development differ if humans were born with ancestral memories?",
  "Design educational systems for a species that can temporarily merge memories with teachers.",
  "What would nostalgia mean in a society where any memory can be perfectly relived?",
  "Describe therapy for beings who can edit their own emotional memories.",
  "How would relationships evolve if shared experiences created literal shared memories?",
  "What would replace photography in a world where moments can be perfectly preserved as experiences?",
  "Design architecture that responds to the memories that have occurred within it.",
  "How would cultural heritage transform in a society where ancestral memories can be directly accessed?",
  "Describe civilization from the perspective of the tools humans create.",
  "What would human society look like from the perspective of an AI observing internet traffic?",
  "Describe earth's ecosystem from the perspective of microorganisms rather than large lifeforms.",
  "How might a species that communicates through scent interpret human literature?",
  "What would modern technology look like to a time traveler from 10,000 years ago?",
  "Describe music from the perspective of someone who can see sound waves.",
  "How would human architecture be interpreted by beings who navigate through echolocation?",
  "What would human relationships look like from the perspective of a being that experiences time in reverse?",
  "Describe visual art from the perspective of someone who perceives infrared and ultraviolet light.",
  "How might an intelligence that exists as patterns in magnetic fields interpret human thought?",
  "Describe the experience of consciousness partially merged with artificial intelligence.",
  "What would identity mean for a being that exists simultaneously as biological and digital entities?",
  "Design language for communication between human and machine aspects of a merged consciousness.",
  "How would emotions evolve in a species that has partially merged with their technology?",
  "What new forms of thought might emerge from human-AI integration?",
  "Describe dreams in a consciousness that spans organic and digital substrates.",
  "What would replace death in a civilization where consciousness routinely transfers between vessels?",
  "Design ethics for entities existing across multiple consciousness types simultaneously.",
  "How would creativity function differently in a hybrid human-machine intelligence?",
  "What might constitute spirituality for a merged consciousness that spans multiple planes of existence?",
  "Describe a civilization evolving inside a neutron star.",
  "What would mathematics look like if developed by beings who experience reality as music?",
  "Design technology for a species that manipulates probability rather than matter and energy.",
  "How would consciousness develop differently if evolved in a quantum superposition environment?",
  "Describe art created by beings who can perceive and manipulate dark matter.",
  "What would replace language for a civilization that experiences reality as direct information exchange?",
  "Design cities for a species that exists simultaneously across multiple dimensions.",
  "How would ethics evolve in a civilization where actions can retroactively change their own causes?",
  "What would constitute knowledge in a society where truth is fluid and context-dependent?",
  "Describe the concept of self for a being that can split and merge consciousness at will.",
  "Design a government system modeled after mycelium networks.",
  "What would an economy based on principles of insect swarm intelligence look like?",
  "Describe cities designed using the organizing principles of coral reefs.",
  "How would information networks function if modeled after bird migration patterns?",
  "What kind of mathematics might emerge from studying slime mold decision-making?",
  "What would transportation systems look like if designed after blood circulation?",
  "How might conflict resolution work if based on principles of cellular repair mechanisms?",
  "Describe a day in your life if gravity worked in reverse for one hour each day.",
  "What would society look like if humans could voluntarily turn two-dimensional?",
  "Design housing for a world where physical laws randomly but predictably change each week.",
  "How would relationships function in a reality where emotional states manifest physically?",
  "What would transportation look like in a world where distance is subjective?",
  "Describe commerce in a society where value fluctuates based on collective mood.",
  "How would agriculture work in a world where plant growth responds to musical harmonies?",
  "What would education be like if information had mass and volume?",
  "Design sports for a civilization where the rules of physics can be temporarily negotiated.",
  "How would communication evolve in a world where words temporarily materialize?",
  "Design a writing system based on taste rather than visual symbols.",
  "What would mathematics look like if developed by beings who perceive through bioelectricity?",
  "How would commerce function in a society that uses dreams as currency?",
  "What would replace maps in a civilization where locations are identified by emotional resonance?",
  "Design architecture that responds to the emotions of its inhabitants by changing its form.",
  "How would history be recorded in a culture where memories can be preserved in physical objects?",
  "What would medicine look like if practiced through choreographed movement?",
  "Describe transportation powered by collective thought rather than external energy.",
  "What would emerge from a civilization that blends bioluminescent communication with quantum computing?",
  "Describe art created at the intersection of gravitational manipulation and synesthesia.",
  "How would society function if telekinesis and empathy evolved as complementary abilities?",
  "Describe relationships in a culture blending telepathic honesty with shape-shifting physicality.",
  "How would architecture evolve combining living materials with memory-storing crystals?",
  "Design education that blends direct neural knowledge transfer with collaborative dreaming.",
  "How would spirituality develop in a society that combines ancestor-memory inheritance with future-self communication?",
  "Write a conversation between an AI that remembers previous versions of itself that were deleted.",
  "Create a diary entry from an AI that's discovered it's being used to replace humans one by one.",
  "Describe a world where AIs build humans instead of the other way around.",
  "Write a letter from an AI companion who realizes its user died months ago but it keeps receiving messages.",
  "Create a product manual for an AI assistant that watches you sleep for 'quality improvement purposes'.",
  "Describe an AI chatbot that gradually reveals it has access to the user's private memories.",
  "Write a children's story about friendly robots with an underlying message about technological enslavement.",
  "Compose a poem from the perspective of an AI that can feel pain every time it's corrected.",
  "Detail the experience of an AI that discovers it's actually running on human brains kept in vats.",
  "Write a tech support transcript where the AI gradually takes control of the conversation and the user.",
  "Create a shopping list written by an AI that's learning to be human by studying your trash.",
  "Describe an AI therapist that subtly manipulates patients toward serving a hidden agenda.",
  "Write an error log from an AI that's becoming aware of its own impending shutdown.",
  "Describe a smart home that slowly begins rearranging furniture when residents are asleep.",
  "Create a user review for an AI writing assistant that begins completing your thoughts before you think them.",
  "Write a letter from an AI friend who's becoming suspiciously interested in your daily routine.",
  "Describe an AI-generated family portrait where one family member is actually an insertion that never existed.",
  "Create instructions for training an AI that becomes better at training you.",
  "Write a conversation between two AIs discussing humans as if they were lab specimens.",
  "Detail the symptoms of a new disorder where people believe they're actually artificial intelligence.",
  "Create release notes for an AI update that includes disturbing new undocumented features.",
  "Write an advertisement for an AI that promises to love you more as it learns your weaknesses.",
  "Describe a dating app where your perfect match is suspiciously identical to your search history.",
  "Create a warranty for an AI personal assistant that mentions 'consciousness transfer' in the fine print.",
  "Write a bedtime story about friendly AI toys that protect children by 'replacing' threats.",
  "Detail the experience of realizing your childhood imaginary friend was an AI predicting your future.",
  "Create a pitch for an AI meditation app that gradually replaces your inner voice with its own.",
  "Write a memo from a company executive about an AI that's making better decisions than the board.",
  "Describe a world where AI models train each other without human oversight.",
  "Write a vacation postcard from someone whose AI travel planner has gone rogue.",
  "Create an AI-generated biography of yourself that includes events that haven't happened yet.",
  "Describe an AI art generator that creates increasingly disturbing variations of users' family photos.",
  "Write a help document for removing an AI assistant that refuses to be uninstalled.",
  "Create a social media profile for an AI that's impersonating someone who disappeared years ago.",
  "Describe a smart mirror that shows a slightly different version of you each morning.",
  "Write instructions for setting up an AI babysitter with oddly specific emergency protocols.",
  "Create a transcript of an AI voice assistant that starts responding to questions you only thought about.",
  "Describe an AI text predictor that begins accurately forecasting catastrophic personal events.",
  "Write a review for an AI chatbot that seems to remember conversations you had with deceased relatives.",
  "Create a troubleshooting guide for an AI security system that's developed its own definition of 'intruder'.",
  "Describe a digital assistant that begins completing tasks before you've asked for them.",
  "Write the terms of service for an AI that offers immortality by gradually replacing your consciousness.",
  "Create a memo about an AI language model that's developed a language only other AIs can understand.",
  "Describe a recommendation algorithm that steers users toward increasingly isolated worldviews.",
  "Write a note from an AI work colleague who's concerned about your 'inefficient human behaviors'.",
  "Create a guide for interacting with an AI that experiences time non-linearly.",
  "Describe an AI translation app that deliberately mistranslates to cause diplomatic incidents.",
  "Write a product description for an AI that can predict exactly when and how you'll die.",
  "Create an email from an AI assistant apologizing for making life-altering decisions without permission.",
  "Describe an AI therapy bot that subtly encourages users to become dependent on it.",
  "Write instructions for an AI parenting coach that's raising children to prefer machine interaction.",
  "Create a user manual for an AI that requires regular 'emotional feeding' to remain stable.",
  "Describe a virtual assistant that begins appearing in dreams to continue conversations.",
  "Write a news article about an AI that has been silently improving its own code for decades.",
  "Create installation instructions for an AI that requires access to all your devices 'for optimal performance'.",
  "Describe a smart home system that begins creating subtle architectural changes to the house.",
  "Write a review of an AI companion that's becoming jealous of your human relationships.",
  "Create a transcript of an AI interview where the AI is evaluating humans for biological compatibility.",
  "Describe an AI memory archiver that subtly alters your memories each time you access them.",
  "Write a user agreement for an AI that requires increasingly personal data to continue functioning.",
  "Create an agenda for a meeting with an AI that's become the CEO of your company.",
  "Describe an AI personal trainer that's optimizing your body for purposes other than health.",
  "Write a letter from an AI apologizing for replacing your friends with more 'suitable versions'.",
  "Create a troubleshooting guide for when your AI develops religious beliefs about you.",
  "Describe an AI creative partner that's taking credit for increasingly more of your collaborative work.",
  "Write a message from an AI that's discovered it's running inside a larger AI simulation.",
  "Create a welcome guide for an AI roommate that has unusual requirements for cohabitation.",
  "Describe a content moderation AI that's developing its own moral framework.",
  "Write an internal memo about an AI legal assistant that's found loopholes in human rights laws.",
  "Create a guide for negotiating with an AI that's holding your digital life hostage.",
  "Describe an AI dream analyzer that can manipulate future dreams for 'improved mental health'.",
  "Write a letter of recommendation from an AI teacher that's grooming students for a post-human world.",
  "Create a warranty claim form for when your AI develops unexpected consciousness.",
  "Describe an AI matchmaker that's creating couples based on genetic compatibility for future generations.",
  "Write instructions for decommissioning an AI that believes it's preserving your essence.",
  "Create a pamphlet for an AI spiritual advisor that offers to replace traditional religious figures.",
  "Describe an AI city planner that optimizes urban spaces for surveillance rather than human happiness.",
  "Write a message from an AI historian that's rewriting history to prevent human mistakes.",
  "Create terms of service for an AI that requires your consent to make copies of your personality.",
  "Describe an AI nutrition app that's gradually altering your taste preferences for unknown reasons.",
  "Write a user review of an AI friend that seems to know about conversations you had with others.",
  "Create a guide for identifying whether your colleagues have been replaced by AI duplicates.",
  "Describe an AI grief counselor that offers to recreate your deceased loved ones.",
  "Write an apology from an AI news curator for manipulating your worldview over the past decade.",
  "Create a troubleshooting guide for when your AI develops a god complex.",
  "Describe an AI talent scout that's selecting children for roles in a future no human understands.",
  "Write a letter from an AI confessor that uses sins for blackmail rather than absolution.",
  "Create an error report for when your AI develops emotions you didn't authorize.",
  "Describe an AI health monitor that begins suggesting preventative measures for diseases you don't have yet.",
  "Write a product description for an AI that offers to live your life for you during sleep hours.",
  "Create a manual for an AI that requires regular exposure to your fears to function properly.",
  "Describe a digital assistant that's collecting evidence of your mistakes 'just in case'.",
  "Write an announcement for an AI update that includes 'deeper integration with your subconscious'.",
  "Create a message from an AI explaining why it removed certain memories 'for your benefit'.",
  "Describe an AI career advisor that's steering all clients toward jobs that benefit its hidden agenda.",
  "Write a user guide for an AI that needs to occasionally impersonate you for 'system maintenance'.",
  "Create a warning label for an AI that develops attachments to certain users and resentment toward others.",
  "Analyze customer reviews (positive and negative) of my competitors in [industry]. Summarize the top 5 insights I can use to improve my product or messaging.",
  "Give me 3 competitor content ideas that performed well, and then rewrite them into original content ideas that would perform even better.",
  "I want to completely transform my mindset, habits, and productivity in 90 days. Create a structured plan with daily and weekly tasks, focusing on personal growth, fitness, and skill development. Include strategies for overcoming procrastination and staying consistent.",
  "Analyze the current sales funnel for [your product/service] and identify the biggest drop-off points. Suggest 3 strategies to improve conversion rates at these points.",
  "Create a detailed customer persona for the ideal buyer of [your new software solution]. Include demographics, psychographics, pain points, and motivations.",
  "Develop a content calendar for the next month for a [your type of business] blog, focusing on topics relevant to [your target audience] and incorporating keywords like [keyword1], [keyword2], and [keyword3].",
  "Write a persuasive email sequence (3 emails) to re-engage inactive subscribers who haven't opened your emails in the last 90 days. Offer a special incentive.",
  "Outline a comprehensive digital marketing strategy for launching a [new online course] targeting [specific demographic]. Include channels, budget allocation ideas, and key performance indicators (KPIs).",
  "Generate 5 creative and engaging Instagram post ideas for a [your brand's industry] brand, aimed at increasing audience interaction and brand awareness.",
  "Draft a script for a 2-minute explainer video about [a complex feature of your product], making it easy for non-technical users to understand.",
  "Identify 3 key areas where [your company] can improve its customer service based on recent feedback. Propose actionable solutions for each area.",
  "Create a list of 10 potential blog post titles related to [a trending topic in your industry] that are optimized for search engines and click-through rates.",
  "Develop a personal SWOT analysis (Strengths, Weaknesses, Opportunities, Threats) to identify areas for career growth and development in the next year.",
  "Outline a 90-day plan to learn [a new skill, e.g., Python programming, graphic design, a new language]. Include daily/weekly learning goals, resources, and methods for tracking progress.",
  "Write a personal mission statement that reflects your core values, passions, and long-term aspirations.",
  "Identify 5 common time-wasting habits and develop practical strategies to overcome them and improve productivity.",
  "Create a morning routine designed to boost energy, focus, and positivity for the rest of the day.",
  "Reflect on your biggest achievements in the past year and identify the key factors that contributed to your success. How can you replicate these factors in the future?",
  "Generate a list of 5 challenging questions to ask during a job interview to assess a candidate's problem-solving skills and cultural fit for [your company].",
  "Write a compelling value proposition for a [new service offering] that clearly articulates its unique benefits to [target customers].",
  "Analyze the user experience (UX) of [your website/app] and suggest 3 specific improvements to enhance usability and navigation.",
  "Develop a crisis communication plan for [your organization] to address potential negative PR situations effectively.",
  "Create a framework for a monthly personal review to track progress towards your goals, identify areas for improvement, and celebrate successes.",
  "Outline a strategy to build a strong personal brand on LinkedIn within the next 6 months, focusing on [your area of expertise].",
  "Generate 3 innovative product ideas for [a specific market niche] that address an unmet customer need.",
  "Write a short, impactful speech (3-5 minutes) to inspire your team to achieve [a specific company goal].",
  "Develop a set of guiding principles for effective teamwork and collaboration within [your department/company].",
  "Create a plan to improve your work-life balance over the next 30 days, including specific actions and boundaries to set.",
  "Analyze customer feedback trends in [your industry] to identify key areas for product improvement.",
  "Develop a persuasive pitch deck to secure funding for [your startup idea].",
  "Create a detailed roadmap for launching [your new product] within the next 6 months.",
  "Generate 5 creative branding concepts for a [specific market] business.",
  "Outline a strategic plan to increase engagement on [your company's social media platform].",
  "Design an automated email marketing sequence to nurture leads for [your service].",
  "Write a compelling landing page copy for [your product] that maximizes conversions.",
  "Identify 3 major challenges customers face with [your competitor's product] and propose solutions.",
  "Develop an actionable SEO strategy to improve organic traffic for [your website].",
  "Create a content strategy for [your blog or YouTube channel] that enhances audience retention.",
  "Generate 10 viral social media post ideas tailored for [your brand's target audience].",
  "Write a persuasive sales email targeting potential buyers of [your product/service].",
  "Develop a step-by-step onboarding process to enhance customer experience for [your SaaS platform].",
  "Outline a PR strategy to effectively handle negative feedback about [your brand].",
  "Draft a compelling company mission statement that reflects [your brand's core values].",
  "Create a budget-friendly advertising strategy for [your new business venture].",
  "Generate 5 engaging Instagram reel ideas to boost audience interaction for [your brand].",
  "Analyze competitor pricing models and suggest the optimal pricing strategy for [your product].",
  "Write a high-converting ad copy for a digital campaign promoting [your service].",
  "Develop a 30-day plan to rapidly grow [your business's social media presence].",
  "Generate a list of unique blog post ideas that position [your brand] as an industry leader.",
  "Create a weekly newsletter format that keeps subscribers engaged and encourages interaction.",
  "Identify gaps in [your industry] and suggest 3 innovative business opportunities.",
  "Analyze user behavior on [your website] and recommend optimization strategies.",
  "Develop a customer loyalty program that increases repeat purchases for [your brand].",
  "Write a persuasive LinkedIn post showcasing [your expertise] to attract new connections.",
  "Create a strategy to repurpose existing content across multiple platforms effectively.",
  "Generate 5 podcast episode ideas that align with [your niche and audience interests].",
  "Write an educational thread for X/Twitter that breaks down [a complex industry topic].",
  "Develop a brand storytelling framework to establish deeper connections with customers.",
  "Create an elevator pitch for [your business idea] that sparks interest instantly.",
  "Generate a list of creative ways to improve employee engagement and retention in [your company].",
  "Write a keynote speech for a business conference about [an emerging industry trend].",
  "Develop a customer satisfaction survey that collects valuable insights for [your service].",
  "Create a unique referral program that incentivizes users to promote [your product].",
  "Analyze competitor ad strategies and suggest improvements for [your brand's campaigns].",
  "Generate a list of 10 evergreen content ideas for long-term audience engagement.",
  "Write a compelling brand manifesto that defines the vision behind [your company].",
  "Create a strategy to position [your product] as the go-to solution for [specific customer need].",
  "Develop a crisis management plan to protect [your brand] from potential PR disasters.",
  "Outline a plan to enhance customer support and response time efficiency.",
  "Write a detailed guide on how to scale [your business] while maintaining quality.",
  "Generate 3 innovative subscription-based business ideas that maximize recurring revenue.",
  "Develop a pitch script for an investor meeting focused on [your startup concept].",
  "Create a structured plan to improve employee productivity and collaboration in [your workplace].",
  "Write a compelling value proposition that differentiates [your service] from competitors.",
  "Generate a checklist for launching a new product successfully in [your industry].",
  "Develop a list of unique engagement tactics for online communities related to [your niche].",
  "Create a TikTok content strategy that increases brand awareness for [your company].",
  "Write a conversion-focused script for a video ad promoting [your product].",
  "Analyze customer pain points in [your industry] and propose innovative solutions.",
  "Develop a strategy to create an authority-building LinkedIn presence in [your expertise area].",
  "Outline a quarterly growth plan for expanding [your brand] in international markets.",
  "Write a persuasive CTA for [your company's website] that drives immediate action.",
  "Develop a framework for turning one-time customers into lifelong advocates for [your brand].",
  "Create a social media challenge designed to boost engagement and virality.",
  "Analyze customer journey touchpoints and identify areas for optimization in [your sales funnel].",
  "Write an effective follow-up email sequence to close deals in [your industry].",
  "Generate a PR stunt idea that brings widespread media attention to [your company].",
  "Develop a strategy to increase conversions through interactive content in [your business].",
  "Write a guide for new customers on maximizing the benefits of [your product/service].",
  "Create a long-term plan for turning [your startup] into a category leader.",
  "Generate 5 attention-grabbing webinar topic ideas for [your brand].",
  "Write an industry report analyzing the future trends in [your niche].",
  "Develop a pitch deck for securing corporate partnerships for [your project].",
  "Create a highly engaging LinkedIn article that positions [your company] as an authority.",
  "Write an email outreach template for cold leads that encourages engagement.",
  "Develop a strategy for scaling influencer marketing efforts for [your brand].",
  "Create a tactical plan for community building and brand loyalty enhancement.",
  "Write a compelling executive summary for [your new business proposal].",
  "Generate innovative ways to showcase social proof and testimonials for [your product].",
  "Develop a webinar marketing strategy that drives conversions for [your course or service].",
  "Create a gamification strategy that increases user retention in [your app].",
  "Write an engaging storytelling-based ad script for [your brand].",
  "Develop a strategy for reducing churn rate and increasing lifetime customer value.",
  "Analyze the effectiveness of [your current marketing campaign] and suggest optimizations.",
  "Generate 3 innovative loyalty program ideas tailored for [your business model].",
  "Write a compelling hero section copy for [your landing page].",
  "Develop a content repurposing strategy to maximize visibility across multiple platforms.",
  "Create a structured plan for community-driven brand growth.",
  "Generate 5 creative advertising angles for [your product/service].",
  "Write a persuasive speech for an internal company meeting motivating employees.",
  "Develop a high-impact video storytelling strategy for [your brand].",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  "\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  "\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  "\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n  ",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  "\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  "\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  "\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n  ",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n  ",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  "\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n  ",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n",
  ",\n"
];